### ISSUE TITLE
createMessage: docs incorrectly list "Array of strings" as parameter

### ISSUE THREAD

**Issue by dmackca** [abalabahaha/eris#1004]
_(This is for v0.13.3, the latest release on npm as of this post; btw the docs on the website say they're for 0.13.2 in the title tag)_

The `Client.createMessage` function [in the docs](https://abal.moe/Eris/docs/Client#function-createMessage) says the `content` parameter can be:

> String | Array | Object
> A string, array of strings, or object. [...]

I wondered if an array of strings might send a random one, but it actually just throws this error:

> No content, file, or embed

It doesn't look like there's anything in the code to check or handle arrays of strings here, but it's mentioned in the comments:
https://github.com/abalabahaha/eris/blob/6d4668cd134d0af6b28a63f9ba3fa2790e28954d/lib/Client.js#L1067

**Comment by bsian03** [comment]
Will fix this in #993
