### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by lem6ns** [abalabahaha/eris#1008]
how do i fix this error? i get it after around 1.5 hours of my bot running

**Comment by bsian03** [comment]
Handle the error, carry on, pretend it never happened.

**Comment by DonovanDMC** [comment]
That's nothing with Eris, and there really isn't anything you can do about it, drop outs will happen with longterm connections, especially on bad networks. I get them all the time, as long as the reconnect/resume happens, you can safely ignore them.

**Comment by lem6ns** [comment]
Ok, thanks
