### ISSUE TITLE
Error when running the install command

### ISSUE THREAD

**Issue by levoothan** [abalabahaha/eris#1023]
C:\Users\rootd\Documents\Bots\Cross-Server-Bot-master>npm install --no-optional eris
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/khaazz/eris.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rootd\AppData\Roaming\npm-cache\_logs\2020-09-26T13_01_48_380Z-debug.log

C:\Users\rootd\Documents\Bots\Cross-Server-Bot-master>

**Comment by ghost** [comment]
You don't have git installed.

**Comment by levoothan** [comment]
> You don't have git installed.

Just realised I did a fresh install of windows and never reinstalled it. Where do I get it again?

**Comment by ghost** [comment]
https://gitforwindows.org/ looks right? i don't personally use windows so your google search might be more helpful than mine.

**Comment by levoothan** [comment]
Seems right. I found it here after a quick search. https://git-scm.com/download/win Thank you.
