### ISSUE TITLE
Pass Shard errors to Client

### ISSUE THREAD

**Issue by feildmaster** [abalabahaha/eris#1029]
Currently Shards have uncaught errors, due to the ShardManager not listening to the (albeit rare) Errors passed by Shards. This results in program failure, and subsequent exit.

The only current workaround is to hook into the error yourself for each Shard.

**Comment by bsian03** [comment]
Stack trace would be helpful here

**Comment by feildmaster** [comment]
Ah, I was wrong. Please ignore, this is my own fault.

Shard does actually pass to client, I wasn't listening to client errors correctly.
