### ISSUE TITLE
Eris 0.14.0 Typescript Issue

### ISSUE THREAD

**Issue by HcgRandon** [abalabahaha/eris#1063]
I receive the follow message when attempting to build my typescript project using Eris 0.14.0:
```
node_modules/eris/index.d.ts(1873,5): error TS2578: Unused '@ts-expect-error' directive.
```

Reproduce:
```
mkdir minimal/ && cd minimal/
npm install eris typescript @types/node
mkdir src/
echo "import * as Eris from 'eris';" > src/index.ts
```

Create a basic `tsconfig.json` and run `tsc` and Error will occur

**Comment by Zorotic** [comment]
I'm also having the same issue.

![image](https://user-images.githubusercontent.com/26655058/98317732-0e9d7180-1fab-11eb-95bd-b766f23aa15b.png)

**Comment by DonovanDMC** [comment]
There's a fix for this in [`eae851a` (#1054)](https://github.com/abalabahaha/eris/pull/1054/commits/eae851a5ab4509b32633d61797810131f62cebc4)

**Comment by Dragory** [comment]
You can also set `"skipLibCheck": true` in your `tsconfig.json` to ignore typing errors from dependencies.

**Comment by HcgRandon** [comment]
@DonovanDMC any idea when this will reach a release? I would like to avoid blanket disabling lib checks. I'm stuck on 0.13.4 till this is fixed

**Comment by DonovanDMC** [comment]
@HcgRandon whenever abal decides to merge #1066

**Comment by bsian03** [comment]
Merged into dev
