### ISSUE TITLE
content.allowed_mentions prevents editing other user's message flags 

### ISSUE THREAD

**Issue by repository** [abalabahaha/eris#1064]
currently if you try editing a another user's message flags, like:
```await message.edit({ flags: 4 });```

it will result in
```DiscordRESTError [50005]: Cannot edit a message authored by another user```

`content.allowed_mentions` is set [here](https://github.com/abalabahaha/eris/blob/814f92b813ef826b70033720e498f9d6092aa670/lib/Client.js#L1021) by eris, commenting this line out allows you to edit flags but breaks allowed mentions functionality

**Comment by bsian03** [comment]
#1007

**Comment by repository** [comment]
#1007 was merged
