### ISSUE TITLE
Gateway Latency

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1073]
How push the Gateway Latency value ?

**Comment by DonovanDMC** [comment]
what

**Comment by apacheli** [comment]
You can see how the gateway latency works [here](https://github.com/abalabahaha/eris/blob/master/lib/gateway/Shard.js#L50).

Please refrain from using the issue tracker for support questions The issue tracker is specifically for bugs and questions surrounding the development of Eris. Use the [Discord server](https://abal.moe/Eris/invite) instead.
