### ISSUE TITLE
Constants docs on website is broken

### ISSUE THREAD

**Issue by JJRcop** [abalabahaha/eris#1074]
https://abal.moe/Eris/docs/Constants doesn't show anything on my device

Eris version of docs 0.14.0
Firefox 78.3.0esr
Debian Testing (bullseye)

all other docs work

**Comment by apacheli** [comment]
Yeap, this is a known issue with the documentation. Unfortunately, no one has control over this. The [reference](https://abal.moe/Eris/docs/reference) page includes some constants, or you can refer to the [source code](https://github.com/abalabahaha/eris/blob/master/lib/Constants.js).

(Abal is very busy, but we can only hope he will fix it)

**Comment by abalabahaha** [comment]
Yeah it's supposed to be `docs/Reference`... Removed the random entry
