### ISSUE TITLE
Message reaction edits message regardless of whether reaction is clicked or not, only works on messages and not embeds (I can't find any example of this, so I could be doing something wrong)

### ISSUE THREAD

**Issue by dps-910** [abalabahaha/eris#1075]
This code here https://hasteb.in/ojexixed.css, I would expect this to show the message "Test", wait until I have reacted, and then edit the message to say "hello". But the message will be edited anyway, even if I have not reacted to the message, like it says in the documentation. Another issue that I have is that reactions do not get added to embeds. I am not sure if this is supposed to happen though. The embed works fine, but the reaction does not get added https://hasteb.in/ugetekax.yaml.

**Comment by DonovanDMC** [comment]
Put code inline, or on a reliable site. I cannot get either of those links to load.

**Comment by dps-910** [comment]
> Put code inline, or on a reliable site. I cannot get either of those links to load.

Here's the code:
```js
client.registerCommand("guildSettings", (msg) => {
  client.createMessage(msg.channel.id, {
    embed: {
      title: "Guild Settings",
      color: 0x000000,
      fields: [
        {
          name: "Prefix",
          value: "🛠",
          inline: false
        },
      ],
    },
  });
}, {
  reactionButtons: [
    {
      emoji: "🛠️",
      type: "edit",
      response: (msg) => {
        client.createMessage(msg.channel.id, {
          embed: {
            title: "Enter prefix",
            color: 0x1496EA
          },
        });
      },
    },
  ],
});
```

**Comment by bsian03** [comment]
What's likely happening is that your bot is capturing itself reacting to the message. You should really filter reactions to only the person who initiated the command.
