### ISSUE TITLE
Discovery splash not implemented

### ISSUE THREAD

**Issue by cyclane** [abalabahaha/eris#1079]
Guilds have a relatively new `discovery_splash` attribute in the [Discord docs](https://discord.com/developers/docs/resources/guild#guild-object-guild-structure) which is not implemented in Eris.

**Comment by bsian03** [comment]
#1033

**Comment by cyclane** [comment]
#1081 - Added attributes to Guild and GuildPreview

**Comment by cyclane** [comment]
Closing since #1081 was merged into dev
