### ISSUE TITLE
Custom requirements inside Command Client

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1082]
It looks like Eris ignores custom requirement inside command client constructor.
<img alt="Docs fragment" src="https://cdn.discordapp.com/attachments/381890266052689920/780370883855384576/Zrzut_ekranu_2020-11-23_o_10.55.08.png">
Sadly, it runs command no matter what. I tried to use it to avoid situation when user types a command on channel where bot can't reply.

I've created a simple function that works fine, but due to Eris error - it can't work well:
<img alt="Eris code fragment" src="https://cdn.discordapp.com/attachments/381890266052689920/780371900626239528/Zrzut_ekranu_2020-11-23_o_10.59.03.png">
<img alt="Permission error" src="https://cdn.discordapp.com/attachments/381890266052689920/780371899279474708/Zrzut_ekranu_2020-11-23_o_10.58.42.png">

Please fix that issue or checks if bot can send message on this channel before command is executed. If no - just return without any message/warning.

**Comment by bsian03** [comment]
What is `this` in that particular context?

**Comment by bsian03** [comment]
OP has a `permissionMessage` set to send a message on invalid perms which is pointing to the same channel which it doesn't have permissions to send messages in. NAB
