### ISSUE TITLE
Help with meme command

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1088]
IM TRYING TO MAKE A MEME COMMAND FOR SOOOOOOOOO LONG

pls just help me

my current code
```
const Discord = require('discord.js');
const randomPuppy = require('random-puppy');

module.exports = class {
    constructor() {
        this.cmd = 'meme',
        this.aliases = ['maymay']
    }

    async run(bot, msg, message, args) {
    const subReddits = ["meme", "me_irl", "dankmeme"]
    const random = subReddits[Math.floor(Math.random() * subReddits.length)];
    const img = await randomPuppy(random);

    msg.channel.createMessage({embed: {
            title: `From /r/${random}`,
            color: 0x55FFCC,
            image: `${img}`
         }})
        return;
    }
}
```

**Comment by ghost** [comment]
The error im getting
``` UnhandledPromiseRejectionWarning: DiscordRESTError [50035]: Invalid Form Body
embed.image: Only dictionaries may be used in a ModelType
at RequestHandler.request (/home/container/node_modules/eris/lib/rest/RequestHandler.js:61:15)
at Darven.createMessage (/home/container/node_modules)......```

**Comment by zerefdev** [comment]
image takes a object with `url` field.
Why do you import a library that you don't use? lol

**Comment by apacheli** [comment]
Please refrain from using the issue tracker for support questions The issue tracker is specifically for bugs and questions surrounding the development of Eris. Use the [Discord server](https://abal.moe/Eris/invite) instead.

**Comment by ghost** [comment]
> image takes a object with `url` field.
> Why do you import a library that you don't use? lol

cus basically i made an economy bot and eris was the easiest and most fun to use... so now im trynna add commands that i never added so yeah 🙃😭

**Comment by ghost** [comment]
> Please refrain from using the issue tracker for support questions The issue tracker is specifically for bugs and questions surrounding the development of Eris. Use the [Discord server](https://abal.moe/Eris/invite) instead.

Oh oki, ima go forward to discord then :D
