### ISSUE TITLE
Discord slash commands

### ISSUE THREAD

**Issue by chaun14** [abalabahaha/eris#1100]
Discord is deploying slash commands.

https://github.com/discord/discord-api-docs/pull/2295/commits/30e6cca446940ca9f51a994f3a9cb63917f7751b#diff-07978ef9d619062fb1afbb70ea065124531246743444f4354cc9e6c8879f8780

**Comment by zerefdev** [comment]
imagine if everyone opened new issue for every new feature. big brain

**Comment by Kio-td** [comment]
I'm currently working with https://github.com/Snazzah/slash-create on my latest bot.
Works well, all you have to do is [attach slash to Eris](https://slash-create.js.org/#/docs/main/latest/examples/discord-bot#with-eris), and then you can use discord.js's commando-style commands (Or just make the commands in the client file too, if that's your cup'o tea.)

It's not full (or hell, even well) documented, but it's really doing the trick (at least for me.)
Additions are welcome to add slash to eris, but until then, I'd recommend using slash-create.

**Comment by dmackca** [comment]
> I'd recommend using slash-create.

@Kio-td This works! But it has a totally different way of handling commands. The `SlashCommand.run` function gets a "context" as its only argument; Any idea how we can access the eris client instance in there, so we can do stuff with eris in the slash-create handlers?

> imagine if everyone opened new issue for every new feature. big brain

Wouldn't that give the eris devs a way to plan and track the new features?

**Comment by zerefdev** [comment]
> Wouldn't that give the eris devs a way to plan and track the new features?

Not really, there are better ways. A new feature is not an "ISSUE".

**Comment by abalabahaha** [comment]
GitHub "issues" are not limited to purely bug reports; try taking a look around GitHub. Coordination already primarily happens in Discord, so issues for every property Discord adds would probably get spammy, but for major new things like this it's fine. No more of this discussion here.

Eris doesn't plan to implement full support for slash commands until the API gets improved+stabilized.

**Comment by Kio-td** [comment]
@dmackca 

> ...The function gets a context- any idea how we can access the eris client instance in there?

Right now, I currently use a module.export with the bot. Normally, I'd name my require("../index.js") serv- so you could do something like serv.bot.getChannel(ctx.channel.id) to get the channel, etc.

Other than that, not really, since Slash-create siphons off of existing event handlers from either D.js or Eris.

EDIT: I should note, slash-create runs independently from Eris, they're completely isolated projects from one another. you're fully able to run Slash-Create with any library that supports rawWS events, or even just through a webserver, which is why I'm unable to say "Oh yeah, ctx.eris right here."- because it's impossible to implement without creating unnecessary burden on the developers.

**Comment by bsian03** [comment]
I'm confused as to why you're not discussing this in the actual repository where the feature was created

**Comment by Kio-td** [comment]
> I'm confused as to why you're not discussing this in the actual repository where the feature was created

Mainly, Ease of access, and trying "not to be that guy that makes you move to the dining room just to talk about what's for dinner".

**Comment by abalabahaha** [comment]
That explanation seems to be of some use to other people exploring their options, so it's fine here. But please move any _further_ discussion about the menu to the dining room, thanks.

**Comment by JustCat80** [comment]
There is a pr draft now #1234

**Comment by abalabahaha** [comment]
Released in 0.16.0
