### ISSUE TITLE
Typings issue with Client.getInvite()

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1118]
Instead of returning the type of `Promise<Invite>`, Eris returns the type of `Promise<never>` when `Client.getInvite()` is used.

**Comment by bsian03** [comment]
Should be fixed in #1054

**Comment by DonovanDMC** [comment]
Works fine when I try it (non-strict).
![image](https://user-images.githubusercontent.com/17226394/103143840-64a5b000-46e4-11eb-8464-d1aeb67877cf.png)

**Comment by bsian03** [comment]
@DonovanDMC They're using a version of eris which doesn't have the aforementioned patch applied - it's the same issue we spoke about in the channel

**Comment by ghost** [comment]
Alright, since it was fixed in another release I'll close this issue now. Thanks.
