### ISSUE TITLE
Misleading "restMode" documentation

### ISSUE THREAD

**Issue by kevinlul** [abalabahaha/eris#1125]
I think the intention is to use different Eris Client objects for gateway bots and REST clients. However, I found that this documentation line is quite misleading.

https://github.com/abalabahaha/eris/blob/72859c9aaf8e7349e06879f2266c8b6885de4720/lib/Client.js#L107

First, it doesn't explain what prefixing means, but this actually means specifying the token type that is passed in the [HTTP Authorization header](https://discord.com/developers/docs/reference#authentication), because the `token` property of client objects, initialized from the options, is directly set as the value for the header.

Second, regardless of whether `maxShards === "auto"`, Eris will automatically prepend the `token` property of the Client object used for REST API calls with `Bot `:

https://github.com/abalabahaha/eris/blob/72859c9aaf8e7349e06879f2266c8b6885de4720/lib/Client.js#L1316-L1321

https://github.com/abalabahaha/eris/blob/72859c9aaf8e7349e06879f2266c8b6885de4720/lib/gateway/Shard.js#L1814-L1817

This means that, contrary to the docs, it is safe to set `restMode: true` in the options when using the Client object to control a bot through the gateway. It's also really convenient to be able to make full use of the `getREST*` methods on same object, especially when the local cache collections fall short!

**Comment by abalabahaha** [comment]
Mostly historical reasons, pre-intents pretty much all objects could be cached without much difficulty, so uses for `getREST*` were rare and usually mistakes. With intents caching is now insanely difficult.  I've updated the wording around this (7a5ec43), will be in next release.
