### ISSUE TITLE
selfbot not emitting ready event

### ISSUE THREAD

**Issue by notnot-nick** [abalabahaha/eris#1133]
It appears that the messageCreate event fires, but the ready event never fires if using user accounts.

**Comment by ghost** [comment]
selfbots are not supported. (also, yeah, that is a known thing that happens; just don't use the ready event.)

**Comment by notnot-nick** [comment]
Huh, it literally has a bunch of user account features, oh well. I was gonna use it to make a discord terminal integration:/
