### ISSUE TITLE
Header error halts any other requests to the endpoint

### ISSUE THREAD

**Issue by Snazzah** [abalabahaha/eris#1137]
Turns out, you can't have certain characters in HTTP headers, leading to this error:

```js
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-Audit-Log-Reason"]
    at ClientRequest.setHeader (_http_outgoing.js:521:3)
    at new ClientRequest (_http_client.js:241:14)
    at Object.request (https.js:314:10)
```

Any other request to the same endpoint (possibly the same bucket) does not respond at all. There is probably some more things to figure about about this, and this is mainly a user issue, but it also shouldn't halt any new requests.

**Comment by bsian03** [comment]
I also fixed this in #1058
