### ISSUE TITLE
Docs show documentation for the dev branch

### ISSUE THREAD

**Issue by Neztore** [abalabahaha/eris#1142]
I've noticed the docs show documentation for the dev branch (In my case it was because [createMessage](https://abal.moe/Eris/docs/Client#function-createMessage) shows `messageReferenceID`, which isn't on master yet )

Is this intentional behaviour? If it is, could it be made more clear? The title of the page is 'Eris 0.14.0' yet some of it is not present in version 0.14.0.

**Comment by abalabahaha** [comment]
Late, but I probably accidentally triggered a deploy one day, sorry about that. Docs are re-deployed with 0.14.0 release now.
