### ISSUE TITLE
Enhancement: PermissionOverwrite should contain permissions

### ISSUE THREAD

**Issue by Gilbert142** [abalabahaha/eris#116]
The PermissionOverwrite object (From GuildChannels) should not only contain a .has method, but also a permission number. Would help out a lot.

(Example: msg.channel has a method to set the permissions number for the (dis)allowed perms, but the property permissionOverwrites doesn't hold the permissions number.)

**Comment by abalabahaha** [comment]
PermissionOverwrite extends Permission, so the allow and deny properties in Permission carry over to PermissionOverwrite. Is this what you are looking for?

**Comment by Gilbert142** [comment]
Yeap, seems that I have to pay a closer look sometimes, thanks!
