### ISSUE TITLE
Stage Channel Type Not Supported

### ISSUE THREAD

**Issue by neowsl** [abalabahaha/eris#1220]
Hi, I'm currently running my Discord bot in my server, and I'm getting a message in the logs:
```
[12:45:47] Cluster 0 | Shard undefined | Error: Unknown guild channel type: 13
{"user_limit":1000,"type":13,"topic":null,"rtc_region":null,"position":2,"permission_overwrites":[],"parent_id":"831364078340407313","name":"🔴 Stream","id":"831367239076020295","bitrate":40000,"guild_id":"831364077875626015"}
```
I checked my Discord server and `🔴 Stream` is a Stage channel. Should I just ignore the message?

**Comment by curtisf** [comment]
Are you running an up-to-date version of eris? What's the version?

**Comment by neowsl** [comment]
I'm using Eris version 0.15.1

**Comment by bsian03** [comment]
This is an issue with eris sharder. You should be using the eris-dev branch. Please head to their repository/server if you're still having issues with this

**Comment by neowsl** [comment]
Alright. Thanks!
