### ISSUE TITLE
Using client.createMessage() then adding reaction to returned promise throws missing access error

### ISSUE THREAD

**Issue by nobu-sh** [abalabahaha/eris#1222]
```js
client.createMessage("some-channel-id", "cool message")
  .then((m) => {
    m.addReaction("some-emoji")
  })
```
Throws the error:
![image](https://user-images.githubusercontent.com/61068742/121078326-6f3d9880-c79e-11eb-9589-eee2178f2a88.png)
however, it adds the reaction to the message perfectly fine
![image](https://user-images.githubusercontent.com/61068742/121078372-7fee0e80-c79e-11eb-892f-ec5ee1672271.png)

and it cannot be caught which is pretty annoying

**Comment by bsian03** [comment]
The error is for something unrelated. You're missing access to whatever guild you're trying to add a role to a member

**Comment by nobu-sh** [comment]
OH SHIT YOU RIGHT. Thats my bad I forgot I had an event listener chilling off to the side doing that ugh. Apologies for wasting time
