### ISSUE TITLE
Unneccesary memory usage in Message.js

### ISSUE THREAD

**Issue by curtisf** [abalabahaha/eris#1247]
In the update function for Message.js, a few properties (embeds, mentions, components for example) are set if the appropriate payload contains them. Even though they are marked as optional in the Discord API docs, I see them passed with every MESSAGE_CREATE. The purpose of this issue isn't to argue whether these properties are passed every time but to bring to light the fact that many of the properties in Message are passed as empty arrays. Eris only checks for `!== undefined`, which means for many instances of Message, there are unnecessary empty arrays being assigned. As a consequence, more memory is used per message which could negatively affect users who cache any large amount of messages in memory.

**Comment by Dramex** [comment]
These empty arrays actually aren't stored in your cache, they are `getters` comes from Message class to force style of code
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by bsian03** [comment]
I'll be honest here, and I know this is from 3 years ago, this should really be brought up with Discord if it's still behaving as mentioned
