### ISSUE TITLE
getDMChannel, channel is undefined or null

### ISSUE THREAD

**Issue by briantanner** [abalabahaha/eris#127]
This is happening to some users, no idea how widespread the issue is.

```
this.client.getDMChannel(user.id)
	.then(channel => this.sendMessage(channel, text))
	.catch(err => this.logger.error(err));
```

**Comment by abalabahaha** [comment]
Still unsure as to why or how this happens. If anyone is able to get more details on this, it would be appreciated.

**Comment by briantanner** [comment]
What I do know about it is that the user doesn't exist in client.privateChannels before or after

**Comment by abalabahaha** [comment]
Seems fixed now
