### ISSUE TITLE
Reactions request promise is delayed

### ISSUE THREAD

**Issue by GuskiS** [abalabahaha/eris#1272]
Reactions promise is delayed after first success. Here is slight demo:
```ts
const emojis = ["1️⃣", "2️⃣", "3️⃣"];

console.time("add");
for (let index = 0; index < emojis.length; index++) {
  console.time("individual");
  await message.addReaction(emojis[index]);
  console.timeEnd("individual");
}
console.timeEnd("add");

console.time("remove");
for (let index = 0; index < emojis.length; index++) {
  console.time("individual");
  await message.removeReaction(emojis[index]);
  console.timeEnd("individual");
}
console.timeEnd("remove");
```
which outputs roughly the same each time I restart bot:
```
individual: 269.83ms
individual: 7.674s
individual: 8.150s
add: 16.095s

individual: 7.270s
individual: 7.647s
individual: 7.696s
remove: 22.614s
```
as you can see, first request completes normally, every other request is delayed.

After logging debug mode, I get these results:
```
1630354860244 MODIFY/channels/879777125937315921/messages/:id/reactions 204: 258ms (230ms avg) | 0/1 left | Reset 1630354867438 (7194ms left)
individual: 259.189ms
1630354867911 MODIFY/channels/879777125937315921/messages/:id/reactions 204: 239ms (226ms avg) | 0/1 left | Reset 1630354875137 (7226ms left)
individual: 7.667s
1630354875681 MODIFY/channels/879777125937315921/messages/:id/reactions 204: 313ms (235ms avg) | 0/1 left | Reset 1630354882835 (7154ms left)
individual: 7.769s
add: 15.696s

1630354883356 MODIFY/channels/879777125937315921/messages/:id/reactions 204: 276ms (236ms avg) | 0/1 left | Reset 1630354890556 (7200ms left)
individual: 7.675s
1630354891258 MODIFY/channels/879777125937315921/messages/:id/reactions 204: 464ms (260ms avg) | 0/1 left | Reset 1630354898430 (7172ms left)
individual: 7.902s
{"op":1,"d":7}
1630354898964 MODIFY/channels/879777125937315921/messages/:id/reactions 204: 271ms (265ms avg) | 0/1 left | Reset 1630354906151 (7187ms left)
individual: 7.706s
remove: 23.283s
```

it seems that request response time is fine, but promise get delayed.

**Comment by DonovanDMC** [comment]
not seeing anything close to that when I run the exact same code
```
individual: 151.473ms
individual: 326.286ms
individual: 391.7ms
add: 870.052ms

individual: 424.457ms
individual: 243.42ms
individual: 275.672ms
remove: 943.906ms
```

branch and commit hash would help

**Comment by GuskiS** [comment]
Running latest version from NPM - `0.15.1`

**Comment by JustCat80** [comment]
you sure it isn't network or something?

**Comment by GuskiS** [comment]
It is happening constantly - each time bot restarts(saving file to trigger changes), I get 1 fast response and others are slow.

**Comment by DonovanDMC** [comment]
seeing it in 0.15.1, not seeing in in https://github.com/DonovanDMC/eris#everything
so clearly it has already been fixed somewhere

not seeing it as bad as that up there, mind you
```
individual: 199.869ms
individual: 1.300s
individual: 1.276s
add: 2.776s

individual: 1.221s
individual: 1.328s
individual: 1.250s
remove: 3.800s
```

**Comment by DonovanDMC** [comment]
Not seeing it in dev, so it has already been fixed
either use dev, or wait for a new release

```
individual: 165.017ms
individual: 351.325ms
individual: 445.807ms
add: 963.033ms

individual: 226.376ms
individual: 256.502ms
individual: 257.237ms
remove: 740.484ms
```

To use dev:
```
npm i abalabahaha/eris#dev
```

**Comment by GuskiS** [comment]
> seeing it in 0.15.1, not seeing in in https://github.com/DonovanDMC/eris#everything
> so clearly it has already been fixed somewhere
> 
> not seeing it as bad as that up there, mind you
> 
> ```
> individual: 199.869ms
> individual: 1.300s
> individual: 1.276s
> add: 2.776s
> 
> individual: 1.221s
> individual: 1.328s
> individual: 1.250s
> remove: 3.800s
> ```

I'm using almost default init:
```ts
const client = Eris(env.bot.secret, { restMode: true });
```
maybe you have something different? I just started with eris - refactored code from discord.js.

When will new version be released?

**Comment by DonovanDMC** [comment]
No eta on a new release. Either wait for one to happen, or install dev and use that.

<details>

   <summary>Client Code</summary>

```js
const Eris = require("eris");

new Eris
	.Client(`Bot ${process.env.TOKEN}`, { intents: ["guildMessages"] })
	.on("messageCreate", async(message) => {
		const emojis = ["1️⃣", "2️⃣", "3️⃣"];

		console.time("add");
		for (let index = 0; index < emojis.length; index++) {
		console.time("individual");
		await message.addReaction(emojis[index]);
		console.timeEnd("individual");
		}
		console.timeEnd("add");

		console.time("remove");
		for (let index = 0; index < emojis.length; index++) {
		console.time("individual");
		await message.removeReaction(emojis[index]);
		console.timeEnd("individual");
		}
		console.timeEnd("remove");
	})
	.connect();
```

</details>

**Comment by GuskiS** [comment]
Having the same ~7s delay with your example.

I think I will wait for the new release, thanks for confirming that this not just me having this issue 👌

**Comment by DonovanDMC** [comment]
> Having the same ~7s delay with your example.

Well yeah, it isn't a end user code thing, it s a lib thing

As I've said, you can install dev and use that

```
npm i npm i abalabahaha/eris#dev
```

Docs for dev are [here](https://abal.moe/ErisDev/docs).

**Comment by bsian03** [comment]
ErisDev is currently running on 0.15.1 docs, Eris is on 0.15.2-dev. Confusing, yes, i know.

**Comment by JustCat80** [comment]
it's now [1.16.0-dev](https://github.com/abalabahaha/eris/blob/dev/package.json#L3)

**Comment by bsian03** [comment]
There is no 1.16.0-dev and docs are still running on 0.15.2-dev

**Comment by bsian03** [comment]
Is this still occuring?

**Comment by coolcalcacol** [comment]
```
individual: 316.541ms
individual: 278.936ms
individual: 462.937ms
add: 1.059s
individual: 304.442ms
individual: 324.503ms
individual: 499.793ms
remove: 1.129s
```
using dono's code running `eris@0.16.1`. So seems fine @bsian03?

**Comment by DonovanDMC** [comment]
Cannot reproduce this issue in **0.17.0**, closing as fixed
```
individual: 235.053ms
individual: 658.409ms
individual: 523.856ms
add: 1.418s
individual: 628.603ms
individual: 716.407ms
individual: 615.13ms
remove: 1.960s
```
