### ISSUE TITLE
Cannot mention users in reply

### ISSUE THREAD

**Issue by neowsl** [abalabahaha/eris#1294]
Is there a way to "reply" to a message when sending one?

![image](https://user-images.githubusercontent.com/63214683/140625684-93e7f0fc-c6b1-4e43-96d0-aedb6222d047.png)

I've tried this:

```ts
		message.channel.createMessage({
			content: "b",
			messageReference: { messageID: message.id },
			allowedMentions: { repliedUser: true }
		});
```

but it's not working.

**Comment by numselli** [comment]
you still need to metion the user in the message content, all that setting allowedMentions does is gives the bot permission to mentions that person in that message

**Comment by DonovanDMC** [comment]
it doesn't work how
does it error, does it do nothing, does it send the message but not reply
and for future reference, issues aren't the place to ask for help, Eris has a [Discord server](https://discord.gg/eris), check out #support

**Comment by bsian03** [comment]
You should also note that messageReference only exists in 0.15.1. As mentioned please join the Discord server if you have questions regarding Eris functionality, we try to keep issues for bug tracking.

**Comment by neowsl** [comment]
Ah ok. Thanks, everyone!
