### ISSUE TITLE
Guilds get 

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1304]
![image](https://user-images.githubusercontent.com/69215407/142215872-f272ee8f-4ce7-4983-b49c-c7fec9f54a88.png)

İ need a get from guild 

```js
 const Guild = Guard.guilds.find(Config.SERVER.GUILD_ID);
  if (!Guild) console.log("Guild not found!");
  ````

**Comment by DonovanDMC** [comment]
find takes a function to filter by

this is basic javascript, we do not teach basic javascript

do not open issues here for basic support, use the [discord server](https://discord.gg/eris)

**Comment by ghost** [comment]
> find takes a function to filter by
> 
> this is basic javascript, we do not teach basic javascript
> 
> do not open issues here for basic support, use the [discord server](https://discord.gg/eris)

Bro you don't have to do it blank, there's nothing about guilds.get in the documentation just tell me how to get guild

**Comment by DonovanDMC** [comment]
> > find takes a function to filter by
> > this is basic javascript, we do not teach basic javascript
> > do not open issues here for basic support, use the [discord server](https://discord.gg/eris)
> 
> Bro you don't have to do it blank, there's nothing about guilds.get in the documentation just tell me how to get guild

Client#guilds is a Collection, collection extends Map
once again basic javascript stuff

**Comment by ghost** [comment]
> > > find takes a function to filter by
> > > this is basic javascript, we do not teach basic javascript
> > > do not open issues here for basic support, use the [discord server](https://discord.gg/eris)
> > 
> > 
> > Bro you don't have to do it blank, there's nothing about guilds.get in the documentation just tell me how to get guild
> 
> Client#guilds is a Collection, collection extends Map once again basic javascript stuff

You don't know anything, you just talk like a remnant and an idiot, and you can go on and contradict what you're saying.

**Comment by DonovanDMC** [comment]
Go read up on what a map is

**Comment by ghost** [comment]
> Go read up on what a map is

Oh, congratulations.

**Comment by d00mster0** [comment]
![map?](https://cdn.discordapp.com/attachments/831967755447828500/910533936340402206/unknown.png)

**Comment by ghost** [comment]
so, so

**Comment by bsian03** [comment]
Both of you need to chill out. Please read the documentation or ask in the discord server before opening an issue here.
