### ISSUE TITLE
how to send private message to everyone in a guild using eris?

### ISSUE THREAD

**Issue by billypentester** [abalabahaha/eris#1312]
I tried the follow code but it's not working :(

let Endpoints = require("eris/lib/rest/Endpoints");
Object.defineProperties(Eris.Client.prototype, {

fetchGuildMembers: {
    value: function(guildID, limit, after) {
      return this.requestHandler.request("GET", Endpoints.GUILD_MEMBERS(guildID), true, {
        limit,
        after
      }).then((members) => members.map((member) => new Eris.Member(member, null)));
    }
  }

})

**Comment by bsian03** [comment]
You're just getting the list of members in the guild? You aren't sending a message, nor are you getting the DM channel itself. 

Please use the support server for questions

**Comment by billypentester** [comment]
If you please guide me on how to get the ID of each guild member

**Comment by bsian03** [comment]
Please use the support server for questions.

**Comment by billypentester** [comment]
link, please

**Comment by bsian03** [comment]
/eris - it's also in the readme

**Comment by billypentester** [comment]
thanks
