### ISSUE TITLE
Member.premiumsince not converted to epoch timestamp

### ISSUE THREAD

**Issue by danny-may** [abalabahaha/eris#1316]
Both the JSdocs and typescript type definition declare that the `Member#premiumsince` property is a numbers, but [discord gives an ISO timestamp](https://discord.com/developers/docs/resources/guild#guild-member-object-guild-member-structure) and the transforms that the Member class does doesnt match the docs.

Member should show the timestamp as a number

**Comment by DonovanDMC** [comment]
joinedAt is converted to a number [here](https://github.com/abalabahaha/eris/blob/dev/lib/structures/Member.js#L75)

**Comment by danny-may** [comment]
Fair point, I misread that and thought it returned a date, updated the issue to just be about `premiumsince`
