### ISSUE TITLE
Eris ignoring bot messages by default?

### ISSUE THREAD

**Issue by aerodevxp** [abalabahaha/eris#1322]
Hey.

I have a bot and on_message simply doesn't seem to register when it's a bot that texts. I even added the ignorebots options to the client definition but nope... I tried Client and CommandClient to no avail.

**Comment by aerodevxp** [comment]
```
                   if(msg.channel.id == '930278911487656006' && bot.user.id == '637531642826719233') //replika
                    {

                        if(msg.author.id == '626901570419818502') //yos
                        {

                            setTimeout(async () =>{
                                const _channel = await bot.getDMChannel('309646978533556225')
                                _channel.createMessage(msg)
                            }, 0)
                        }
    
                    }
```

code I used to detect the message from the bot and transfer it somewhere else.

**Comment by JustCat80** [comment]
first of all you should use the discord support server for things like this https://discord.gg/Eris Second, the event is  `messageCreate` isn't it?
https://abal.moe/Eris/docs/0.16.1/Client#event-messageCreate

**Comment by HeadTriXz** [comment]
Message content will become a privileged intent and is disabled by default. Make sure to enable it through the Developer Portal and use the correct intents in your client's options.

**Comment by DonovanDMC** [comment]
> Message content will become a privileged intent and is disabled by default. Make sure to enable it through the Developer Portal and use the correct intents in your client's options.

This does not apply currently in any gateway below v10, and we're using v9

**Comment by bsian03** [comment]
It also sends a messageCreate with an empty data for the relevant fields. But besides the issue, so marking these off topic

**Comment by aerodevxp** [comment]
> first of all you should use the discord support server for things like this https://discord.gg/Eris Second, the event is `messageCreate` isn't it? https://abal.moe/Eris/docs/0.16.1/Client#event-messageCreate

yes my bad it's messageCreate
