### ISSUE TITLE
Folder Mapping Deprecation

### ISSUE THREAD

**Issue by Coolguy3289** [abalabahaha/eris#1329]
Hi All,

We're using Eris 0.16.1 with Node v16.13.1, and when we start our process, we're getting the following in console originating directly from the Eris package:
```node:70288) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /project/node_modules/eris/package.json. Update this package.json to use a subpath pattern like "./*". (Use `node --trace-deprecation ...` to show where the warning was created) ```

Trying the basic fix by googling that deprecation (changing the export from "./" to "./*" ends up breaking eris with a bunch of "MODULE NOT FOUND" errors, so I figured I'd post this here to see if anyone has been working on a fix for the next release of eris. 

Thanks,
Coolguy

**Comment by rilysh** [comment]
Probably inside package.json, need to updated from `./` to `./*`, you can do it manually as well.
![image](https://user-images.githubusercontent.com/71683721/151298581-1faf9a85-0d13-4c53-84cb-558b218aa4dd.png)

**Comment by Coolguy3289** [comment]
I tried that is what I meant. It just broke Eris all together

**Comment by bsian03** [comment]
Fixed in #1508/#1509
