### ISSUE TITLE
disableEvents Typings

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1349]
`ClientOptions#disableEvents` seems to have no typings. This leads to no IntelliSense which is annoying because you have to search up the different events.

**Comment by DonovanDMC** [comment]
it has no typings because these are raw event names, and no one wanted to write out a full list of them - it's just easier to let people look at Discord's docs
It also isn't really worth it because `disableEvents` is mostly obsoleted via intents

**Comment by bsian03** [comment]
working as intended
