### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Meenic** [abalabahaha/eris#1352]
When I try to use createGuildCommand, it returns with this error:

```js
TypeError: Cannot read property 'id' of undefined
    at IMClient.createGuildCommand (C:\Users\pc\Desktop\invite-fetcher-master\node_modules\eris\lib\Client.js:636:94)
    at C:\Users\pc\Desktop\invite-fetcher-master\bin\framework\services\Commands.js:109:25
    at CommandsService.init (C:\Users\pc\Desktop\invite-fetcher-master\bin\framework\services\Commands.js:116:11)
    at C:\Users\pc\Desktop\invite-fetcher-master\bin\client.js:162:68
```

Currently using `Eris 0.16.1`, typescript `4.4.4`

**Comment by ghost** [comment]
Are you calling `createGuildCommand` before the client emits `ready` event?

**Comment by Meenic** [comment]
> Are you calling `createGuildCommand` before the client emits `ready` event?

yes

**Comment by ghost** [comment]
Call the function after the client emits the `ready` event

**Comment by Meenic** [comment]
alright i got it know thanks

**Comment by ghost** [comment]
Generally, for such issues you should ask in eris's support server. This is not the place. [link](https://discord.gg/eris)
