### ISSUE TITLE
`editMessage` and `editWebhookMessage` send attachments twice in the same request

### ISSUE THREAD

**Issue by TheEssem** [abalabahaha/eris#1356]
When using `Client#editMessage`, `Client#editWebhookMessage`, or anything that depends on these functions (e.g. `CommandInteraction#editOriginalMessage`), the `file` key is not stripped from the input object. This results in attachments being sent over simultaneously in raw binary form via the `file` form data entry, and as a JSON array converted from a Node buffer in the `payload_data` entry:

![image](https://user-images.githubusercontent.com/21112968/161178071-adc6dada-55c1-432d-b8d9-df12640d967d.png)

This can result in requests that are much larger than they should be (e.g. a 4MB request being inflated to 16MB). It would probably be a good idea to remove `file` from the options object in `RequestHandler#request` if the file argument is also present.

**Comment by bsian03** [comment]
#1285 resolves this
