### ISSUE TITLE
Guild.permissionsOf will error if the member is not cached

### ISSUE THREAD

**Issue by Nuckyz** [abalabahaha/eris#1392]
If the member is not an instance of Member, `member.id` and `member.roles` will both thrown an error.

https://github.com/abalabahaha/eris/blob/dev/lib/structures/Guild.js#L1119
```js
 permissionsOf(memberID) {
        const member = typeof memberID === "string" ? this.members.get(memberID) : memberID;
        if(member.id === this.ownerID) {
            return new Permission(Permissions.all);
        } else {
            let permissions = this.roles.get(this.id).permissions.allow;
            if(permissions & Permissions.administrator) {
                return new Permission(Permissions.all);
            }
            for(let role of member.roles) {
                role = this.roles.get(role);
                if(!role) {
                    continue;
                }

                const {allow: perm} = role.permissions;
                if(perm & Permissions.administrator) {
                    permissions = Permissions.all;
                    break;
                } else {
                    permissions |= perm;
                }
            }
            return new Permission(permissions);
        }
    }
```

**Comment by DonovanDMC** [comment]
there isn't really anything we can do about this

**Comment by abalabahaha** [comment]
Yeah, we need to know what roles the Member has to calculate perms, so it needs to be cached or fetched

**Comment by frobinsonj** [comment]
A possible solution would be to return `Permission(0)` and emit a warning/error?

**Comment by Nuckyz** [comment]
> A possible solution would be to return `Permission(0)` and emit a warning/error?

Adding into this, I don't think this issue should be kept. As of now it is misleading that the code will always succeed, when in reality it has a chance of erroring. Returning null would not make a difference for Javascript users, but it would cause errors for Typescript. The above solution would avoid errors without making any breaking changes to both Javascript and Typescript users. Though, perhaps we could also return the permissions for the @everyone role instead of 0?

**Comment by DonovanDMC** [comment]
Returning 0 or some other permission would be returning false information back to the bot, which we don't want to do

The code would have no way of knowing if we just couldn't resolve the permissions

**Comment by DonovanDMC** [comment]
> As of now it is misleading that the code will always succeed, when in reality it has a chance of erroring.

This is how eris works

The VAST, and I do mean vast majority of functions will not return null, they will error if something is wrong

This is perfectly valid behavior
