### ISSUE TITLE
Incorrect typings for Member#communicationDisabledUntil

### ISSUE THREAD

**Issue by danny-may** [abalabahaha/eris#1400]
Discord documents the communication_disabled_until property as being undefined, null, or an ISO date string, and eris respects this at runtime. The typings however do not, and declare the property as `null | number` instead of `null | undefined | number`

https://github.com/abalabahaha/eris/blob/dev/index.d.ts#L638
https://github.com/abalabahaha/eris/blob/dev/index.d.ts#L3097

**Comment by bsian03** [comment]
#1399
