### ISSUE TITLE
Forum channels

### ISSUE THREAD

**Issue by Spappz** [abalabahaha/eris#1418]
Eris doesn't recognise forum channels ([channel type](https://discord.com/developers/docs/resources/channel#channel-object-channel-types) 15). Without digging around the code too much, I'd assume the first file of import would be [Constants.js](https://github.com/abalabahaha/eris/blob/dev/lib/Constants.js#L111), but since I don't know whether forums operate considerably differently from other channels in the API I can't assist any further right now

I am able to respond to interactions within forum threads using `interaction.createMessage()`, but I'm getting some mysterious errors otherwise. I don't know what's _causing_ these errors, they seem to just occur sporadically.
> Error: Unknown guild text channel type: 15
> at new Guild (.../eris/lib/structures/Guild.js:138:41)
> at Map.add (.../eris/lib/util/Collection.js:61:19)
> at Shard.createGuild (.../eris/lib/gateway/Shard.js:115:42)
> at Shard.wsEvent (.../eris/lib/gateway/Shard.js:1198:40)
> at Shard.onPacket (.../eris/lib/gateway/Shard.js:405:26)
> at Shard._onWSMessage (.../eris/lib/gateway/Shard.js:2457:29)
> at WebSocket.emit (events.js:400:28)
> at Receiver.receiverOnMessage (.../ws/lib/websocket.js:1178:20)
> at Receiver.emit (events.js:400:28)

There's a bunch of PRs open and I'm under the impression some amount of refactoring is being done, so apologies if you're already aware of this!

**Comment by coolcalcacol** [comment]
yeah forums are mhm

**Comment by doomestee** [comment]
Quite the opposite, the library is dead as there hasn't been a lot of activity so far. There's a lot of missing features, especially the message content intent. Unless you see any new major commit, consider the lib dead de facto.

**Comment by Spappz** [comment]
rip

Good luck with everything else then, and thanks for the library while it lasted 🙏
