### ISSUE TITLE
"this" becomes client after client connect.

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1422]
If you ever tried write eris bot with classes you will see "this" keyword becomes to client and all class variables becomes undefined because eris binds "this" keyword to client right after client connected. This issue makes almost impossible using OOP in eris. It is also ruined my all day because I dont understand why my class variables dont working after client connected?

**Comment by ghost** [comment]
If you want to see an real world example check this out: https://github.com/EndChapter/7-24-classical-music-bot

**Comment by abalabahaha** [comment]
I assume you're referring to your event listeners? This is a Javascript quirk; class methods aren't bound to class objects by default. You can bind it when registering the listener:

```js
this.client.on("ready", this.ready.bind(this));
```

or in the constructor:

```js
class Client {
  constructor() {
    this.ready = this.ready.bind(this);
  }
  method() {
    this.client.on("ready", this.ready);
  }
}
```

**Comment by ghost** [comment]
I mean check the code I used this as client...

**Comment by ghost** [comment]
And I dont bind anything!

**Comment by ghost** [comment]
Eris binds Client to "this" keyword

**Comment by ghost** [comment]
This is a bug not a question.

**Comment by ghost** [comment]
If you ever look the bind's documentation It makes other variables undefined if you use with this keyword in strict mode

**Comment by ghost** [comment]
And It makes my all variables undefined you can try to add variables in that class and try to use after client connected

**Comment by ghost** [comment]
It doesnt make any sense right? Just try it! This is why I opened the issue!

**Comment by ghost** [comment]
I am referring Eris Client.js line 240 btw
![image](https://user-images.githubusercontent.com/93621798/202215411-efdfdda0-e169-4bfb-b1d8-dea40105b928.png)

**Comment by bsian03** [comment]
> And I dont bind anything!

Unless there is a massive misunderstanding, abal is telling you that binding the method is the fix?

Also please just use one reply if you want to say something. You can edit if you forget to add something and is still relevant to what you originally said. It's annoying for people who receive email notifications to these issues

**Comment by ghost** [comment]
> Unless there is a massive misunderstanding, abal is telling you that binding the method is the fix?

That is really my bad I am really sorry for misunderstanding you abal :(

> Also please just use one reply if you want to say something. You can edit if you forget to add something and is still relevant to what you originally said. It's annoying for people who receive email notifications to these issues

I will thanks!
