### ISSUE TITLE
50001 Error

### ISSUE THREAD

**Issue by BeamCodingComplex** [abalabahaha/eris#1443]
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

DiscordRESTError [50001]: Missing Access
    at RequestHandler.request (C:\Users\Samuel\Downloads\main-bot1.0\main-bot1.0\node_modules\eris\lib\rest\RequestHandler.js:75:15)
    at Client.createGuildCommand (C:\Users\Samuel\Downloads\main-bot1.0\main-bot1.0\node_modules\eris\lib\Client.js:656:36)
    at file:///C:/Users/Samuel/Downloads/main-bot1.0/main-bot1.0/dist/discord.js:461:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I am currently confused on how to fix this and any help is higly appricated.

**Comment by DonovanDMC** [comment]
Get access

**Comment by BeamCodingComplex** [comment]
do you know how im new  ?

**Comment by Christian-Toney** [comment]
To be more specific, your bot doesn't have permission to make guild commands. When adding your bot to the server, make sure your bot has access to the `applications.commands` scope.

![image](https://user-images.githubusercontent.com/37517470/214372545-ed6f982d-0abc-42dd-81f6-175c4ff391b4.png)

You can make a link to give your bot permissions by going to https://discord.com/developers/applications, selecting your bot, going to Oauth2, then URL Generator.

**Comment by BeamCodingComplex** [comment]
> To be more specific, your bot doesn't have permission to make guild commands. When adding your bot to the server, make sure your bot has access to the `applications.commands` scope.
> 
> ![image](https://user-images.githubusercontent.com/37517470/214372545-ed6f982d-0abc-42dd-81f6-175c4ff391b4.png)
> 
> You can make a link to give your bot permissions by going to https://discord.com/developers/applications, selecting your bot, going to Oauth2, then URL Generator.

Still giving the same error which sucks? Any other idea, is it a server error?

**Comment by bsian03** [comment]
Please consult the discord API documentation or ask in the discord developers server.
