### ISSUE TITLE
Get access? 50001 Fix?

### ISSUE THREAD

**Issue by BeamCodingComplex** [abalabahaha/eris#1444]
Get access
I was given this answer, I spent trime trying to find its meaning, I am reallly sorry if this is looking like a dumb issue for me but can anyone give me a clear answer I enabled intents and gave my discord bot full permission to the server.

_Originally posted by @DonovanDMC in https://github.com/abalabahaha/eris/issues/1443#issuecomment-1400856064_

**Comment by coolcalcacol** [comment]
Seek access. Pertain access. Get access.

**Comment by bsian03** [comment]
Next time please don't open the same issue twice.
