### ISSUE TITLE
Bot doesn't connect to discord.

### ISSUE THREAD

**Issue by clonedr0id** [abalabahaha/eris#1454]
Console:
![image](https://github.com/abalabahaha/eris/assets/102883031/cd791625-4307-49bb-89bc-bd0930b471ed)
And here is my code:
![image](https://github.com/abalabahaha/eris/assets/102883031/f3af33ee-3deb-42f3-9323-b493e4e8d20e)

pls explain why the bot doesn't connect :(

**Comment by DonovanDMC** [comment]
>extends Eris

I don't know why you have this here if you're making a client separately and assigning it to a variable, but your issue lies there
You aren't passing a token to the `super` call

**Comment by YalphaFR** [comment]
I'm think you doesn't really know how extends class run.  Change 2 parts to your code : 

`
constructor() {
 super(new Eris(...))
 this.commands = ...
 this.events = ...
}


run() {
  this.connect();
}`

**Comment by egedemirkiran** [comment]
You're creating 2 separate client with `super` call and Eris. If you want to create a Client with super, you have to pass token to the `super`. Btw, you can access the client created with `super` using `this` in the LOLO class.
If you want to create a just 1 Client, here is the Example;
```javascript
import Eris from 'eris';

class Test extends Eris {
    constructor (token, options) {
        super(token, options);

        this.connect()
        this.once('ready', () => console.log('Ready!'));
    }
}

const client = new Test('DISCORD_BOT_TOKEN', {
    intents: ['guilds', 'guildMessages'],
    maxShards: 'auto'
});
```
