### ISSUE TITLE
oldMember on "guildMemberUpdate" returns null on the first call

### ISSUE THREAD

**Issue by astroctrl** [abalabahaha/eris#1456]
I'm using it to detect role changes in user but if it's the first guildMemberUpdate call it will return null, making my code useless as if it was a old role won't be detected.
Possible solution for my case would be caching all members but that would be a waste of memory

**Comment by DonovanDMC** [comment]
This isn't a library bug, it's how Discord works
Eris can't do anything about it
caching all members IS the solution, if you absolutely need the data

**Comment by astroctrl** [comment]
Well time to cache thousands of users, thank you. Sorry for opening the issue!
