### ISSUE TITLE
Invalid OGG magic string

### ISSUE THREAD

**Issue by Catbirby** [abalabahaha/eris#146]
After getting mpeg set up and setting things up with a selfhost music bot that I have been working on I got an odd crash. It was suggested that I open an issue here.

```[Tue Dec 27 2016 17:43:34 GMT-0800 (STD) LOG] Invite: https://discordapp.com/oauth2/authorize?client_id=245389624724291584&sc
ope=bot&permissions=120654848
[Tue Dec 27 2016 17:43:35 GMT-0800 (STD) LOG] Ready!
[Tue Dec 27 2016 17:43:45 GMT-0800 (STD) LOG] Dispatching command 'queue' with arguments [https://www.youtube.com/watch?v=dEr
T7dz2Y24]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Invalid OGG magic string: ����
    at OggOpusTransformer.process (/mnt/c/Users/ellis/Documents/Bots/Tricobot/Hamster-master/node_modules/eris/lib/voice/stre
ams/OggOpusTransformer.js:19:20)
    at OggOpusTransformer._transform (/mnt/c/Users/ellis/Documents/Bots/Tricobot/Hamster-master/node_modules/eris/lib/voice/s
treams/OggOpusTransformer.js:83:28)
    at OggOpusTransformer.Transform._read (_stream_transform.js:167:10)
    at OggOpusTransformer.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at OggOpusTransformer.Writable.write (_stream_writable.js:247:11)
    at PassThrough.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at PassThrough.emit (events.js:188:7)```

**Comment by abalabahaha** [comment]
Very little data on this, could just be the randomness of the internet

**Comment by Catbirby** [comment]
Yeah, not too sure, I've only ran into it twice

**Comment by cernodile** [comment]
I've also encountered this, but only from a file playback?

**Comment by cernodile** [comment]
My theory about this is that, ytdl-core, which I and assumingly he is using, downloads a track, that ffmpeg recognizes as OGG, therefore finds invalid data, and throws the error?

**Comment by abalabahaha** [comment]
doubt it

**Comment by cernodile** [comment]
Well, doesn't ytdl-core download .mp3 audio, or something? The error shouts OGG, which is already another format of audio.

**Comment by macdja38** [comment]
@Lunar-Skies do you happen to have the code that caused malfunction available?

**Comment by Catbirby** [comment]
@macdja38 https://github.com/Catbirby/Hamster it happened while I was trying to run my musicbot code
I still run into the issue every so often, and it causes the code to come to a complete halt.

**Comment by abalabahaha** [comment]
If it's crashing the process, you need to add an error event handler to the voice connection

**Comment by lewisakura** [comment]
I'm getting the same here, using `node-ytdl-core`.

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Invalid OGG magic string: ���
    at OggOpusTransformer.process (/root/Akane/node_modules/eris/lib/voice/streams/OggOpusTransformer.js:19:20)
    at OggOpusTransformer._transform (/root/Akane/node_modules/eris/lib/voice/streams/OggOpusTransformer.js:83:28)
    at OggOpusTransformer.Transform._read (_stream_transform.js:167:10)
    at OggOpusTransformer.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at OggOpusTransformer.Writable.write (_stream_writable.js:241:11)
    at PassThrough.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at PassThrough.emit (events.js:191:7)
```

I was already prepared for this thing, so my bot didn't halt.

Code used:
```js
bot.joinVoiceChannel(voiceChannel).then((vc) => {
                            bot.createMessage(
                                channelID,
                                "Playing your song!"
                            );
                            try {
                                vc.play(ytdl(args[1], {quality: "highest"}));
                            } catch (e) {
                                bot.createMessage(
                                    channelID,
                                    "EXCEPTION: " + e.message
                                );
                            }
                        }).catch((err) => { 
                            bot.createMessage(
                                channelID,
                                "An error occured while attempting to join that voice channel. Try joining a different one, then run the command again! " + err
                            );
                            return;
                        });
```
(indents are horrible i know, voiceChannel is a pre-determined ID)

**Comment by abalabahaha** [comment]
Does this happen consistently with the same OGGs, or just random? If it's consistent, can someone link a few?

**Comment by lewisakura** [comment]
It seems to be consistent with node-ytdl-core for me, but I'm not sure about anyone else.
Links I've tried to use with ytdl:
https://www.youtube.com/watch?v=wcPBXvDV7ZE
https://www.youtube.com/watch?v=WUqap2fnZlo
https://www.youtube.com/watch?v=PKfxmFU3lWY

**Comment by macdja38** [comment]
that's... odd... I don't see OGG anywhere on the youtube formats list, though I could just be missing it https://en.wikipedia.org/wiki/YouTube#Quality_and_formats

**Comment by BrunoMoreira99** [comment]
@macdja38 I think it's `Vorbis` audio encoding.

> In the Ogg multimedia framework, Theora provides a lossy video layer. The audio layer is most commonly provided by the music-oriented Vorbis format or its successor Opus. Lossless audio compression formats include FLAC, and OggPCM.

https://en.wikipedia.org/wiki/Ogg

**Comment by macdja38** [comment]
@BrunoMoreira991 ohh lol that explains everything... ytdl reports a container type of ogg... and an encoding of vorbis... that container that contains vorbis instead of opus... @abalabahaha 's lib sees the ogg container and assumes someone tried to feed it opus... that's why their is an invalid header...

**Comment by macdja38** [comment]
@LunarSkies idk if you still exist, but if so... either... don't do it the way your doing it, check to see if the video has a formats thing before feeding it in, and if it's got a formats thing that's ogg, remove it... if you don't want to... put the encoding in the encoding param (it may be with ytdl by default) and give this branch a shot. https://github.com/macdja38/eris/tree/patch-2

**Comment by abalabahaha** [comment]
Invalid **OGG** magic string. Not Opus magic string.

Ogg container pages always begin with "OggS". This is unrelated to having Vorbis packets in the page.

Also, if it was an Ogg Vorbis file, eris would [throw an `Invalid codec` exception](https://github.com/abalabahaha/eris/blob/6a7ba67b2f45253225fd9097938a93462b59705d/lib/voice/streams/OggOpusTransformer.js#L68)

**Comment by abalabahaha** [comment]
Haven't got any recent complaints on this, and don't see any glaring issues that could cause this. Feel free to comment/reopen if this is still an issue.
