### ISSUE TITLE
Getting display name but NOT server nickname

### ISSUE THREAD

**Issue by old-df38257622** [abalabahaha/eris#1494]
Hello! I'm writing a bot that, among other things, uses server nicknames, and if there's no server nickname, falls back to a username. I can't find anything on this and was wondering if there's a way to get the user's *display name* - not just their *username* like in the image below.
![image](https://github.com/abalabahaha/eris/assets/46039037/b45467c8-240e-4a15-84b2-5373e3621296)
Thanks!

**Comment by bsian03** [comment]
Install the dev branch (beware of breaking changes) and use displayName.
Please use the [server](https://discord.gg/Eris) for support questions in the future
