### ISSUE TITLE
Suggestion: Message.suppressEmbeds(bool)

### ISSUE THREAD

**Issue by Jaesaces** [abalabahaha/eris#1506]
Function on a message object that suppresses or unsuppresses the embeds on that message.

This is one of the message flags in the developer docs:
https://discord.com/developers/docs/resources/channel#message-object

**Comment by conorwastakenwastaken** [comment]
What's wrong with just using editMessage to suppress/unsuppress embeds? It's pretty straightforward imo

**Comment by Jaesaces** [comment]
Fair enough, obviously I looked into it enough to find the requisite message flag in the discord docs, but it just felt weird that the option to remove embeds was buried that far

**Comment by bsian03** [comment]
It's kinda annoying but yeah, use the flag to suppress embeds
