### ISSUE TITLE
PrivateChannel class that doesn't work for the "typingStart" event

### ISSUE THREAD

**Issue by Akinator31** [abalabahaha/eris#1507]
I use this class to check that a Channel is a private message. I use it to display the status "is writing ..." when a user starts writing in his ticket as a private message.

The problem is that the if that checks whether the "Channel" attribute is an instance of the privateChannel class returns false every time, even when the Channel is a private message.

I removed this comparison and it works, but the bot displays the status "is writing" regardless of the Channel the user is writing in, whereas this should only be the case for private messages.

Extract from the code I use:

if (config.typingProxy && (**__channel instanceof Eris.PrivateChannel**__)) {
        const thread = await threads.findOpenThreadByUserId(user.id);
        if (! thread) return;
        try {
          await bot.sendChannelTyping(thread.channel_id);
        } catch (e) {}
      }

**Comment by DonovanDMC** [comment]
you'll never get an intact dm over the gateway, check if `type` is undefined instead

**Comment by Akinator31** [comment]
That's what I tell myself but when I print "channel", I get an object but I don't know what it corresponds to.

Like this :

  parentID: '11207080827191858',
  nsfw: false,
  permissionOverwrites: Collection(5) [Map] {
    '28464678364387553' => PermissionOverwrite {
      allow: 3072n,
      deny: 0n,
      id: '28464683643287553',
      type: 1
    },
    '11207046300967226942' => PermissionOverwrite {
      allow: 1049600n,
      deny: 0n,
      id: '112070430767226942',
      type: 0
    },
    '1120704201362576114' => PermissionOverwrite {
      allow: 1024n,
      deny: 1048576n,
      id: '11207042016782776114',
      type: 0
    },
    '1120704635675664180' => PermissionOverwrite {
      allow: 1049600n,
      deny: 0n,
      id: '1120704630970364180',
      type: 0
    },
    '1143984619523574443' => PermissionOverwrite {
      allow: 1049600n,
      deny: 0n,
      id: '1143984619527804443',
      type: 0
    },
    baseObject: [class PermissionOverwrite extends Permission],
    limit: undefined
  },
  rateLimitPerUser: 0,
  topic: null,
  messages: Collection(0) [Map] {
    baseObject: [class Message extends Base],
    limit: 100
  },
  lastMessageID: '12439638459051585627',
  lastPinTimestamp: null
}

**Comment by Akinator31** [comment]
So I don't know how to filter messages to display the status "is writing..." only to users who write in their private message between themselves and the bot.

**Comment by DonovanDMC** [comment]
That's a guild channel, a dm channel will *always* only have an id

As I said, check if type is undefined

**Comment by Akinator31** [comment]
Channel is not undefined, it's an object. But I solve my problem by add an other parameter in the if.

Eris.PrivateChannel doesn't work correctly I think.

Thanks a lot for your help.
