### ISSUE TITLE
hey bsian please read this

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1514]
I'm gonna send ya something, just read it, okay? My buddy sent it to me, but I didn't read it 'cause... well, just didn't. First, say what ya want three times, then read this thing below... Oh yeah, gotta say what ya want three times first, got it? In the big man upstairs' name or whatever. Say there's no power but His, got it? Amen... Now, send this to like 20 folks, your wish will come true or whatever. I didn't buy it, but hey, it works, apparently. If you delete it or don't send it, well, good luck with your dreams, buddy. Now check your watch, in 9 minutes, you'll be smiling or something... it's easy, just copy and send. Let's see if it does anything. Give it a whirl for me.

**Comment by stopitbsian** [comment]
Oh also, there are over 10 bugs in the library after merging your PR/s. Good job!
