### ISSUE TITLE
Voice state not added when the bot starts

### ISSUE THREAD

**Issue by flav-code** [abalabahaha/eris#1522]
If I'm connected to a channel and it starts, the bot doesn't add a voiceState.
before the update, it worked fine
https://github.com/abalabahaha/eris/pull/1521

**Comment by bsian03** [comment]
karma got me here.

just to confirm, you're in the voice channel already when the bot READYs?

**Comment by flav-code** [comment]
yes i'am in the voice channel, then i start the bot and the voiceState is empty

**Comment by flav-code** [comment]
If I reconnect to the channel, that settles it, but I need it to be there at startup.
