### ISSUE TITLE
Remove these warnings if you don't use this class.

### ISSUE THREAD

**Issue by flav-code** [abalabahaha/eris#1526]
![image](https://github.com/user-attachments/assets/4667dae3-e43d-49a5-939c-5d3d767bfbe8)

**Comment by bsian03** [comment]
Am looking for a solution for this. 

On an unrelated note, you shouldn't be linking warns to error logs

**Comment by flav-code** [comment]
i didn't link it it's emit on the stderr

**Comment by abalabahaha** [comment]
09d1ba9
