### ISSUE TITLE
Expose newly_created on THREAD_CREATE event

### ISSUE THREAD

**Issue by MaSp005** [abalabahaha/eris#1568]
The [Discord API passes the property](https://discord.com/developers/docs/events/gateway-events#thread-create) `newly_created: true` on a THREAD_CREATE gateway event. As of 0.18.0, this property is not exposed in the `threadCreate` event on `Eris.Client`.

Since the event is fired multiple times for one thread's creation, this property allows the application to distinguish the duplicate emitted events without having to manually track the IDs of created threads.

This could either be implemented by adopting and exposing said property in [`ThreadChannel#update`](https://github.com/abalabahaha/eris/blob/dev/lib/structures/ThreadChannel.js#L32) or by passing it as another argument in the emitted event in [`Shard.js:2159`](https://github.com/abalabahaha/eris/blob/dev/lib/gateway/Shard.js#L2159).

**Comment by bsian03** [comment]
added to #1464
