### ISSUE TITLE
[DEV BRANCH] SharedStream - Broken VoiceConnection removing

### ISSUE THREAD

**Issue by cernodile** [abalabahaha/eris#157]
BRANCH: dev

VERSION: latest

If you remove a voice connection from SharedStream, it doesn't disconnect, and if you do disconnect it, rest of voice channels in the SharedStream stop getting audio input until next time play() is executed. I believe it has something to do with unfinished handling of disconnects and unclosed websockets.

**Comment by abalabahaha** [comment]
You sure this isn't related to the months-old Discord client bug where you stop hearing a bot when it leaves a voice channel in a mutual server? (until you rejoin the channel)

**Comment by cernodile** [comment]
Well, I can rejoin channel, but still won't hear anything.

**Comment by cernodile** [comment]
Seems like Discord end bug after testing with 2 accounts.
