### ISSUE TITLE
Avatar size [help]

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#164]
May I ask

Which commands allows me to get the URL of picture with original size of the user avatar? Not the 128x128 one?

Thanks

**Comment by hsiW** [comment]
You really can't honestly theres no real way to as far as I know.

**Comment by ghost** [comment]
The KawaiiBot developer told me "eris provides it". His bot uses some commands to make a meme with the user avatar pic in high quality. Now I'm surprised.

**Comment by hsiW** [comment]
He was wrong.

**Comment by AlexFlipnote** [comment]
My bad

**Comment by hsiW** [comment]
only thing that really exists is adding `?size=2048` or whatever you want onto the end of the avatar url, which isn't a eris thing
