### ISSUE TITLE
Possible issue with self bots

### ISSUE THREAD

**Issue by SamEm** [abalabahaha/eris#17]
As of a few hours ago my selfbot stopped readying up. No change in code or anything, it just stopped.
Two other bots on the same connection and using the same library work fine. If I change the self tag and use a bot token on the code, it works. Ran an empty bot with only the `ready` event but nothing happend.
After a while I get this error `[Error: Existing connection detected]`

Possible issue with self bots?

**Comment by rekkih** [comment]
By reading that error, this might also affect sharding with a main server logging everything that a shard can't. (e.g. full server count)
