### ISSUE TITLE
Subcommands cannot delete messages.

### ISSUE THREAD

**Issue by Ocky-Public** [abalabahaha/eris#176]
Hi there,

I noticed that subcommands cannot control the deletion of their command message like top level commands can.

A simple test: Register any commands in this configuration:
bot -> command (deleteCommand: false) -> subcommand (deleteCommand: true)

if you then call **command subcommand** the command message wont be deleted.

Only top level commands can control deletion of the command message it would seem. 
Since Command.regiterSubcommand has the deleteCommand variable, is this intentional?

Thanks

**Comment by abalabahaha** [comment]
Whoops, forgot to actually comment.

No, it's not intentional, I'll merge the fix sometime soon.

**Comment by Ocky-Public** [comment]
Thanks for the quick work. o7
