### ISSUE TITLE
How to Ignore other bot's command use?

### ISSUE THREAD

**Issue by Hoto-Cocoa** [abalabahaha/eris#178]
i tried use `bot.user.bot` but it return `true` everytime.

**Comment by Brayzure** [comment]
Depends. If you're not using the CommandClient, you can check whether the message author is a bot (something like `msg.author.bot` would work). If you *are* using the CommandClient, you can specify that you want to ignore bots by doing `new CommandClient(token, {ignoreBots: true})` when you create the client.

Of course, adapt the code I posted to fit with what you already have.

Edit: I think I understood what you meant, let me know if I missed the mark at all.

**Comment by Hoto-Cocoa** [comment]
Thanks. That correctly work!

**Comment by aerodevxp** [comment]
Hi... I have a bot, not commandclient, that ignores bots no matter what??
