### ISSUE TITLE
Collection.remove doesn't always clear the wanted object from the collection.

### ISSUE THREAD

**Issue by Ovyerus** [abalabahaha/eris#183]
This appears to be inconsistent to which collections it happens to, however with testing I have discovered that this issue persists across restarts and always happens to the collections it originally happened to in the first place, and only those ones.

![Screenshot](https://all.foxgirlsare.sexy/570747.png)

**Comment by Brayzure** [comment]
Perhaps the client is immediately adding the object back to the collection. Although I can't seem to find the relevant file, I would imagine that any time the client receives voice data, it checks to see if the connection is present in that collection, and adds it if it isn't.

Aside from that, I can't imagine why you would want to directly remove an object from a collection in the first place.

**Comment by Brayzure** [comment]
Found the issue after a quick chat in the Discord chat, just posting here for the record. `Collection.remove()` takes an object with `id` as a parameter, whereas `.delete(id)` is a native method of a Javascript Map, which is what should be used here.

**Comment by Ovyerus** [comment]
I'm a dum dum
