### ISSUE TITLE
inlineVolume ?

### ISSUE THREAD

**Issue by SomeoneCares11** [abalabahaha/eris#185]
Hi, 

What is inlineVolume becouse 
`connection.setVolume(0.2);`
not working with me!!
all other connections functions works, and there no error massage !

**Comment by MergHQ** [comment]
You need to enable `inlineVolume` when you want to play something in the voice channel. Otherwise `connection.setVolume` won't work.

**Comment by SomeoneCares11** [comment]
How can i enable it?

**Comment by MergHQ** [comment]
set `inlineVolume` to true in the play option object: https://abal.moe/Eris/docs/VoiceConnection#function-play

**Comment by SomeoneCares11** [comment]
I didn't see that, i took 2 hours looking for inlineVolume in google i thought its an FFMPEG option
Solved, thank you !
