### ISSUE TITLE
createMessage() doesn't work with JSON

### ISSUE THREAD

**Issue by Ovyerus** [abalabahaha/eris#19]
No error is thrown, but no message is sent either. I've tried this is with tables and arrays.

**Comment by mnlkrs** [comment]
What exactly do you mean with "doesn't work with JSON" ?

**Comment by abalabahaha** [comment]
If a JS object is passed as content, the lib will try to use object.content as the actual content. If object.content doesn't exist nothing will be sent. If you want to send the object as a string, object.toString() or JSON.stringify(object)
