### ISSUE TITLE
localStorage.token isn't a thing anymore 

### ISSUE THREAD

**Issue by GNUGradyn** [abalabahaha/eris#202]
Uncaught ReferenceError: localStorage is not defined
    at <anonymous>:1:1
(anonymous) @ VM438:1

I'm logged in and viewing a guild, also tried it on the login page

**Comment by hsiW** [comment]
what are you even trying to do

**Comment by hsiW** [comment]
if you're trying to do what i think 

1. Open Discord
2. Press Ctrl+Shift+i
3. Click "Application" tab
4. Expand Storage > Local Storage > https://discordapp.com
5. Find "token" under "key"
6. Copy the text in quotes on the same row

**Comment by abalabahaha** [comment]
The section in the docs needs updating :3

**Comment by podechorarkk** [comment]
What's this for?

**Comment by LJNeon** [comment]
What's this comment for? (credit to Jacob_Bolda#4211)
