### ISSUE TITLE
user.avatarURL still sometimes throws error

### ISSUE THREAD

**Issue by macdja38** [abalabahaha/eris#203]
https://sentry.pvpcraft.ca/share/issue/322e32343833/

Click full on the top right of the stack trace to see the error's origin.

In different context this time. The proceeding issue was picked up on a private message. That said the code included only parses private messages, so it is possible it is present on other message creates.

Note that bot was run without force fetch all members, with a small sample size of servers.

Possibly relevant https://github.com/abalabahaha/eris/issues/196

**Comment by abalabahaha** [comment]
0785129 might fix this

**Comment by macdja38** [comment]
Probably does, I'm not running it in production right now but I have not seen it since. I'll create another issue when/if I see this pop up again.
