### ISSUE TITLE
Commands not deleting when deleteCommand is set to true when invalid usage, error, permission, or cooldown messages are returned.

### ISSUE THREAD

**Issue by LJNeon** [abalabahaha/eris#209]
Also invalid usage command says to use help <command> even when defaultHelpCommand is disabled.

**Comment by LJNeon** [comment]
![screenshot 2017-03-12 at 5 51 41 pm](https://cloud.githubusercontent.com/assets/23249107/23837884/a2226012-074c-11e7-8a0c-34c444761640.png)
Here's an example.

**Comment by AggPro** [comment]
same here.

**Comment by abalabahaha** [comment]
@AggPro if you're talking about the issue in the title, that is fixed in 0.7.0. This is being kept open because of the invalid usage message bug in the description.
