### ISSUE TITLE
Feature Request : calling client.message.author.createMessage(message) would automatically resolve the Author's Direct Message Channel

### ISSUE THREAD

**Issue by sr229** [abalabahaha/eris#215]
This would simplify some of the code.

A example would be a help message.

Normally you would do:
```js
client.msg.author.getDMChannel();
dm.createMessage('test');
```
But this would be narrowed down to
```js
client.msg.author.createMessage('test');
```
This promotes simplification and code cleanliness too.

You can close if this is too vague

**Comment by abalabahaha** [comment]
Seems unnecessary to add this to the lib, but you could always modify the prototype in your code :eyes:
