### ISSUE TITLE
get member instead of user

### ISSUE THREAD

**Issue by SomeoneCares11** [abalabahaha/eris#221]
Hi,

i want to get mentioned member instead of mentioned user,

i try in many ways, didn't work, could you help me please ?

Thank you

**Comment by abalabahaha** [comment]
`Guild.members` is a Collection of Member objects, so you could get the Member object associated with a user ID using that.

If you have more questions, [the Discord channel](https://discordapp.com/invite/n2g6BQP) is a better place to get help from.
