### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN gateway.discord.gg:443

### ISSUE THREAD

**Issue by TheEvilSocks** [abalabahaha/eris#223]
Happens when my server loses the internet connection or if the DNS servers are acting up.
Running on commit eecd8d8
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN gateway.discord.gg:443
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by Fuechschen** [comment]
You are supposed to handle that error in your code. It's emitted through the error-event

**Comment by TheEvilSocks** [comment]
In my opinion this should be handled under the autoreconnect option that can be passed to the constructor.

**Comment by Fuechschen** [comment]
This error indicates something is wrong with your connection, so it would be pointless to just reconnect since this usually happens, when something bigger breaks down and reconnect attempts would just be a waste of resources. 
If you really want it to reconnect without checking where the problem is, just add a `client.connect();` to your error handler, however, i strongly recommend not to do this

**Comment by abalabahaha** [comment]
The above comment isn't really correct. It should already be attempting a reconnect when you see this error, but the error is emitted anyway to tell you something is happening. NodeJS will throw unhandled error events as process errors, so If you want to continue reconnecting, add an error event listener that logs the error (or something like that).

**Comment by TheEvilSocks** [comment]
Interesting mechanic, thanks for the help!

**Comment by KirillBorunov** [comment]
> This error indicates something is wrong with your connection, so it would be pointless to just reconnect since this usually happens, when something bigger breaks down and reconnect attempts would just be a waste of resources. If you really want it to reconnect without checking where the problem is, just add a `client.connect();` to your error handler, however, i strongly recommend not to do this

It may be a temporal connection issue that is not under my control (ISP problems). This happened just now and the bot was not tried to reconnect, just was running doing NOTHING. I restarted it and it connected OK (without changing anything on the connection config from my side).
So if it try to reconnect automatically, then will be no problem and not need to do anything from my side.
Why you suggest to not do so? Maybe in theory you are right, but in the real world a simple reconnect will solve this.
