### ISSUE TITLE
bot.token return to false !

### ISSUE THREAD

**Issue by SomeoneCares11** [abalabahaha/eris#224]
Hi, 

the command bot.token its must return to the token of the bot, i dont know why its return to FALSE ?
any help?

**Comment by Aux** [comment]
Hello abal wanted me to ask you what this means thanks

**Comment by SomeoneCares11** [comment]
on the docs : 
https://abal.moe/Eris/docs/Client
bot.token should return to the bot token, 
its return to FALSE, i dont know what does it mean

Thanks.

**Comment by abalabahaha** [comment]
Well I don't see anything in Eris that could be causing this, so you are probably accidentally setting it to false somewhere in your code.

In the future, asking questions in [the Discord channel](https://discordapp.com/invite/n2g6BQP) is a better way to get help

**Comment by SomeoneCares11** [comment]
Sorry my mistake it was  if statement, i figred out the token stars with 4 letters `Bot `
Solved.. sorry again
