### ISSUE TITLE
Voice connections persisting after guild delete

### ISSUE THREAD

**Issue by briantanner** [abalabahaha/eris#228]
After a while of running, I begin to notice voice connections for guilds that the bot is no longer in. Similarly, I noticed voice connections for guilds that do exist with a null channelID.

**Comment by abalabahaha** [comment]
Are the connections with null channelID connected/ready/playing?

**Comment by briantanner** [comment]
Not ready, playing, or connecting.

**Comment by abalabahaha** [comment]
Can you check if dev (5bb6a59) fixes this
