### ISSUE TITLE
Voice connection failing to init crashes process

### ISSUE THREAD

**Issue by macdja38** [abalabahaha/eris#233]
Initializing a voice connection to a voice server that the bot fails to connect to or one which has an expired https cert causes an uncaught exception. 
Example of issue: https://sentry.dvguild.tk/share/issue/362e383934/
Example of horribly patched together fix that does not really work but stops process crashing: https://github.com/macdja38/eris/commit/e4823cb87aafd70364d1f96a870ce3cfa871f4c2

**Comment by abalabahaha** [comment]
How'd the voice WS make it so far without an error handler :thinking: 
Should be fixed by 3f6565d
