### ISSUE TITLE
Shard's memory usage

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#236]
Hello, I recently realized that in other **libs** there is the option to know how much memory each _shard_ is using, if possible, **gentlemen**, add this _beautiful and glamorous_ experience to eris.

**Comment by abalabahaha** [comment]
Can you provide an example of a lib that does this?

**Comment by LucasLeandro1204** [comment]
@abalabahaha [https://discord.js.org/#/docs/main/stable/class/Shard](Discord.js)

**Comment by LucasLeandro1204** [comment]
@abalabahaha [Discord.js](https://discord.js.org/#/docs/main/stable/class/Shard)

**Comment by briantanner** [comment]
you can do this in node yourself... `process.memoryUsage()` as well as `os.freemem();` and `os.totalmem();` with the node os module among other things...

**Comment by abalabahaha** [comment]
In NodeJS, is not feasible to get the memory usage of an object (Shard), but only the total memory usage of a process. I believe discord.js spawns a process per shard, and uses process.memoryUsage() to get _per-process_ memory stats (not specifically _per-shard_, but it just happens to work out this way). Eris will not handle cross-process sharding for you, but you can spawn one process for each shard with the `child_process` module.

**Comment by ghost** [comment]
Thanks for help.
