### ISSUE TITLE
Automatically generated Typescript typings

### ISSUE THREAD

**Issue by cryptiklemur** [abalabahaha/eris#237]
Would be a wonderful thing to have.

**Comment by abalabahaha** [comment]
same tbh

**Comment by TTtie** [comment]
Honestly, that idea should be realized as soon as possible

**Comment by aurieh** [comment]
Working on it at [aurieh/eris-typings](https://github.com/aurieh/eris-typings).
Still missing several features, like the eris factory (default export), webhook and embed types (`any` right now). As it's handwritten, it might (and will) have some issues.

EDIT: all done properly 🙏

**Comment by abalabahaha** [comment]
Manually generated typings have been added, however automating typing generation through the doc generator is planned.
