### ISSUE TITLE
How can I make my bot send Friend Requests?

### ISSUE THREAD

**Issue by AggPro** [abalabahaha/eris#238]
# Welp, I would like to test something, and this code right here...

> var friendCommand = bot.registerCommand("friend", (msg, args) => {
    if(args.length === 0) {
        msg.author.addRelationship;
           return ":ok_hand:";
    }
}, {
    description: "Creates a Relationship With the bot",
    fullDescription: "Helpful for some testing",
    usage: ""
});
# ...returns this!
> addRelationship(block) {
        return this._client.addRelationship.call(this._client, this.id, block);
    }
### I would love if anyone helped me.
                                                     -Agg

**Comment by minemidnight** [comment]
Well, you didn't call anything and bots cannot use relationships. All you did was reference a function

**Comment by AggPro** [comment]
but theres in the docs! 
https://abal.moe/Eris/docs/Client#function-addRelationship

**Comment by hsiW** [comment]
That should be removed in the future, bots cannot use `addRelationship` and if a userbot/selfbot uses `addRelationship` it unverfies your account.

**Comment by AggPro** [comment]
oh.

**Comment by AggPro** [comment]
anyways thanks

**Comment by franz-liszt** [comment]
to avoid unverifying your account, update the user agent in https://github.com/abalabahaha/eris/blob/master/lib/rest/RequestHandler.js to some browser one, take your own browser user agent
