### ISSUE TITLE
Best way to update Client's configuration at runtime

### ISSUE THREAD

**Issue by Coriou** [abalabahaha/eris#242]
Hey. 

My use case is being able to change the Client's settings which are passed through the constructor at runtime.

I couldn't find a method built-in Eris to do this, so I looked at [Client.disconnect() ](https://abal.moe/Eris/docs/Client#function-disconnect) but it doesn't return anything (so I don't know when it's safe to actually restart a connection using a new client).

Is there a recommended way to do this ?

Thanks !

**Comment by abalabahaha** [comment]
I mean, you could modify Client.options, but that won't always work.

Why do you want to update Client config at runtime?

**Comment by Coriou** [comment]
Well in my case it's because I want to edit options via an interface. A good ol' "restart" would work fine in my case; however I find that the connection status isn't so predictable.

Here's what I mean about the connection status (and, especially, disconnecting): 

I run [Client.disconnect()](https://abal.moe/Eris/docs/Client#function-disconnect) -> it will loop through each shard and disconnect them, or try. It will throw a socket exception if a shard is currently connection for instance. And, it will not return anything once the connection is indeed dead. Not to mention that sometimes, most likely because of overlapping socket statutes, it will not actually disconnect.

I also tried doing it like Eris is doing it: get all shards, loop through them, check their status, and if need be, fire a [Shard.disconnect()](https://abal.moe/Eris/docs/Shard#function-disconnect) then keep looping until all my shards return a "disconnected" status. However, even if I pass the `options.reconnect : false` to the [Shard.disconnect()](https://abal.moe/Eris/docs/Shard#function-disconnect) method, if the main client has been initialized with the `options.autoreconnect: true` option, it will still try to reconnect in some cases. 
Don't get me wrong: the auto-reconnect feature is insanely useful, but I think it just should be a tad smarter when you actually want to disconnect so it's doesn't try to reconnect you thinking the connection was lost.

I understand easily that changing options at runtime is a specific use-case that probably shouldn't need to be implemented within Eris core, and devs should make their own implementation if they need it (which I believe, most won't). However, and this is linked for me, I think a better support for disconnecting would be super cool :)

_And, while I'm here and already hogging public space, I'll take the opportunity to thank you - and everyone else involved in this project - for the great library you put up, much better than any other I've tried. Awesome work !_

**Comment by abalabahaha** [comment]
Hmm... that disconnect behavior sounds like a bug. I'll look into that later.

Depending on which options you want to modify, changing some options will immediately change them everywhere. Other options may require a disconnect and connect, and some options can't be changed until you restart the process.

**Comment by abalabahaha** [comment]
Sorry for being super late, but if you still care:

On dev branch, the shard connection queue should now be cleared when calling Client.disconnect(), so it should be safe to assume all shard connections are terminated immediately after Client.disconnect(). Changes in dev branch should be landing in a release sometime in the next week.

**Comment by Coriou** [comment]
Hey, no problems and yeah, I still care ! I'll check it out ! Thanks :)

**Comment by abalabahaha** [comment]
I'll assume this is fixed, do comment if it's still not.
