### ISSUE TITLE
Voice Connections not deleted from cache after disconnected

### ISSUE THREAD

**Issue by minemidnight** [abalabahaha/eris#245]
The `bot.voiceConnections` collection has 278 connections cached yet only 16 where the connection has not ended.

**Comment by abalabahaha** [comment]
Needs repro steps

**Comment by macdja38** [comment]
Steps to reproduce:
1. create a bunch of voice connections
2. call .destroy or .disconnect on them (I forget which)
3. That's that!

(That's what I gather from talking to them in chat earlier, they probably didn't notice .disconnect disappearing from the docs)

**Comment by DasWolke** [comment]
I usually use bot.voiceConnections.leave(guildId) as a temp workaround, this seems to work fine for me

**Comment by abalabahaha** [comment]
You're supposed to use `Client.leaveVoiceChannel()` :|
