### ISSUE TITLE
CommandClient.registerGuildPrefix doesn't replace "@mention " with the bot's actual mention

### ISSUE THREAD

**Issue by pyrox18** [abalabahaha/eris#248]
Using "\@mention " in the CommandClient's commandOptions replaces it with the bot's actual mention correctly, but it doesn't replace itself when used with registerGuildPrefix.

Here's a snippet that can reproduce the problem:
```javascript
bot = new Eris.CommandClient("someBotToken", {}, {
  prefix: ["+", "@mention "]
});

bot.registerCommand("test", (msg, args) => { // Registers "@mention " as the guild prefix
  bot.registerGuildPrefix(msg.channel.guild.id, "@mention ");
  return "Test";
});

bot.registerCommand("ping", "Pong!");

bot.connect();
```

In Discord:
![screen shot 2017-06-17 at 7 06 31 pm](https://user-images.githubusercontent.com/21293289/27252396-244eec4c-5390-11e7-87da-9b1c52cd59f5.png)

After changing the guild prefix with `+test`, nothing happens when I try to run the ping command by mentioning the bot, but literally typing `@mention ping` works.

This also doesn't work when an array of prefixes is supplied as an argument:
```javascript
bot.registerGuildPrefix(msg.channel.guild.id, ["~", "@mention "]); // doesn't work
```

Using the CommandClient's inherited user property is possible as a workaround, though, so it might be that the method just isn't replacing "\@mention " correctly.
```javascript
bot.registerGuildPrefix(msg.channel.guild.id, bot.user.mention + " "); // this works
```

**Comment by pyrox18** [comment]
I did some testing with the registerGuildPrefix method and seem to have found the cause. The method always registers the supplied prefix(es) due to this.preReady always being true, and the "@mention" regex replace calls are always skipped.

```javascript
// ...
registerGuildPrefix(guildID, prefix) {
    if(this.preReady){ // set to true in the constructor (this.once("shardPreReady", ...))
        this.guildPrefixes[guildID] = prefix;
    } else { // this entire block is skipped, and "@mention" is never replaced as a result
        if(Array.isArray(prefix)){
            for(var i in prefix){
                prefix[i] = prefix[i].replace(/@mention/g, this.user.mention);
            }
            this.guildPrefixes[guildID] = prefix;
        } else {
            this.guildPrefixes[guildID] = prefix.replace(/@mention/g, this.user.mention);
        }
    }
}
// ...
```

Removing the `if(this.preReady)` statement would solve the problem, but I'm not sure if it will have any unintended effects elsewhere, so I'll just leave it as it is here.

**Comment by relative2** [comment]
@pyrox18 The `if(this.preReady)` statement might have supposed to say `if(!this.preReady)` because it wouldn't be able to get the this.user.mention if `this.preReady` wasn't true. I don't know if that's the case though

**Comment by abalabahaha** [comment]
Sorry for not getting to this for a while. #260 is now merged into the dev branch, and should land in a release sometime in the next week.
