### ISSUE TITLE
[Feature Request] Modify volume of VoiceConnection

### ISSUE THREAD

**Issue by Ratismal** [abalabahaha/eris#25]
Hi,

I've been using this library's voice capabilities, and was wondering if it would be possible to modify the volume of a VoiceConnection? As VoiceConnection#playRaw() already iterates through the stream, I believe it would be possible to modify the buffer there by a volume variable before emitting it to discord. This would save users from having to implement methods to modify their streams beforehand. I hope you consider adding this. Thank you for your time.

Sincerely,
ratismal (stupid cat)

**Comment by cernodile** [comment]
Must have. Sometimes streams can play on really low volume.
