### ISSUE TITLE
VoiceConnection:end fires too early when playing ytdl stream

### ISSUE THREAD

**Issue by Ovyerus** [abalabahaha/eris#254]
This could possibly be an issue with node-ytdl itself, or just my implementation, however I'm putting this here *juuust* in case.
Basically, as the title says, when playing a stream from node-ytdl (eg. `cnc.play(ytdl('youtube.com/somelink'), ...)`), the `end` event seems to fire maybe 30 seconds too early than it should. I have tested this (with my system at least), and it appears to be somewhat inconsistent, and *only* happens to streams from ytdl.

**Comment by DasWolke** [comment]
Could be the notorious econnresets, which you get from YouTube sometimes. ytdl-core tries to resume the stream but does not always succeed.

**Comment by abalabahaha** [comment]
You really shouldn't be relying on ytdl's built-in streamer at scale. Does this happen if you use ytdl.getInfo and pass the url from that?

**Comment by Ovyerus** [comment]
Huh, no. I'll try that out.

**Comment by Ovyerus** [comment]
So turns out I wasn't using ytdl's stream function, because I was manually picking a quality, I was using `got.stream(...)`, and all the other audio sounds (soundcloud, clyp, etc.) use this same method however they don't end early. Passing the url directly to `cnc.play` seems to be working without any early skipping.

**Comment by abalabahaha** [comment]
If passing the URL directly and other audio streams work fine, it seems like eris is not at fault here.
