### ISSUE TITLE
Session is no longer valid reconnect loop

### ISSUE THREAD

**Issue by macdja38** [abalabahaha/eris#255]
https://sentry.io/share/issue/3138363633362e333034323638313639/
Click "full" for full stack trace. 

It seems that discord Disconnects Eris with the error Invalid Session ID, then Eris simply reconnects with that session id... accumulates a few hundred failed connections pretty quickly.

**Comment by macdja38** [comment]
Close code 4006

**Comment by hsiW** [comment]
This seems to be able to be replicated by having the bot play a sharedStream in a voice channel then deleting said voice channel

**Comment by abalabahaha** [comment]
Should be fixed by 85af7d7
