### ISSUE TITLE
null role in guildRoleDelete event

### ISSUE THREAD

**Issue by macdja38** [abalabahaha/eris#256]
https://sentry.io/share/issue/3138363633362e333034343639353931/

role emitted was null. 

Docs for event: https://abal.moe/Eris/docs/Client#event-guildRoleDelete

**Comment by abalabahaha** [comment]
How often and when does this happen? I'm hesitant about modifying this behavior because there really shouldn't be a case where the client doesn't have a role cached, since all roles are sent during GUILD_CREATE and aren't chunked like members are.

**Comment by macdja38** [comment]
I get at least once a day, the session resume thing caused the bot to get rate limited on sentry sometimes so idk if their were more of them.
