### ISSUE TITLE
CommandClient's reaction buttons will not work if the command sends an embed

### ISSUE THREAD

**Issue by relative2** [abalabahaha/eris#258]
CommandClient's [`onMessageReactionEvent`](https://github.com/abalabahaha/eris/blob/dev/lib/command/CommandClient.js#L173) will return if there is not `msg.content`. When you only send an embed and no text outside of the embed, `msg.content` won't exist, but `msg.embeds` will.

**Comment by LJNeon** [comment]
Would this be fixed just by removing the `|| !msg.content` or does that create another problem?  In which case checking for attachments and embeds too would fix it?

**Comment by relative2** [comment]
@LJNeon I edited it so that I changed `|| !msg.content` to `|| (!msg.content && !msg.embeds)`
i don't know if I messed up on logic there though

**Comment by LJNeon** [comment]
Wouldn't messages with only an attachment have an empty or no msg.content, which would also fail?

**Comment by relative2** [comment]
@LJNeon ~~someone would have to check. the content may be a CDN url~~
Actually, the content is type `string` and it is just blank, so you'd have to check that.

**Comment by abalabahaha** [comment]
Sorry for not getting to this for a while. #260 is now merged into the dev branch, and should land in a release sometime in the next week.
