### ISSUE TITLE
channel.delete() errors aren't caught

### ISSUE THREAD

**Issue by MichaelTheriot** [abalabahaha/eris#261]
```
try {
  channel.delete();
} catch (err) {}
```

Results in the following when my bot lacks permission to delete a channel:

```
(node:8448) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 403 FORBIDDEN on DELETE /channels/334554701485965322
```

**Comment by abalabahaha** [comment]
Try-catch only works for synchronous functions that throw errors. API calls in Eris are asynchronous and return Promises. Error handling in Promises is done through the `catch()` callback (example below). If you want, you can [read more about using Promises on the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises).

```
doStuff().catch(function(err) {
    console.error("o no an error", err);
});
```

**Comment by MichaelTheriot** [comment]
It's an asynchronous error.

```js
(async function () {

  try {
    channel.delete();
  } catch (err) {}

})();
```

Test case:

```js
const Eris = require('eris');
const bot = new Eris(token); // bot doesn't have delete voice channel permission

bot.on('ready', async function () {
  try {
    bot.guilds.get(guildid).channels.get(channelid).delete();
  } catch (err) {}
});

bot.connect();
```

**Comment by abalabahaha** [comment]
If you want to use async with this, you must also `await` the Promise:
```js
(async function () {
  try {
    await channel.delete();
  } catch (err) {}
})();
```

**Comment by MichaelTheriot** [comment]
Wow noob mistake on my part. ty
