### ISSUE TITLE
User bots are taking up huge amounts of RAM.

### ISSUE THREAD

**Issue by LJNeon** [abalabahaha/eris#265]
This was mentioned in the Discord API server by John#0969.

A reference point made by John is that an identical user bot run with discord.js would take up under 20MB when he used it.

- John is in 15 guilds and only one of them is large and the example on eris's homepage is using just over 500MB and takes a while to ready when run.  (All optional libs installed)
- I'm in 93 guilds with over 20 of them being large (including the ten biggest discord servers atm), and my selfbot also uses just over 500MB and takes 2-5 minutes to ready when run.  (All optional libs installed)
- alexa#4444 mentioned that they were in ~20 guilds and their selfbot used 130MB.  (optional libs unknown)
- NoobLance™#3500 mentioned that they were in 80 guilds and their selfbot tended to use over 500MB.  They mentioned that testing atm their selfbot used ~320MB.

Screenshots I could find:  (first is NoobLance, then John, then the last two are mine)
![](https://images.discordapp.net/attachments/178672669841948672/336679222984572928/unknown.png)
![](https://images.discordapp.net/attachments/291011841348468737/336603000992956426/unknown.png)
![](https://images.discordapp.net/attachments/291011841348468737/336613147337293824/Screenshot_2017-07-17_at_1.59.55_PM.png)
![](https://images.discordapp.net/attachments/291011841348468737/336608194854125568/Screenshot_2017-07-17_at_1.40.15_PM.png)

**Comment by TTtie** [comment]
Can agree. My selfbot hogs up around upto ~160 MB of the RAM on ready event, when everything is loaded, after few minutes from it it gets to approx 80 MB.

![image](https://b1nzy.good-me.me/f25912.png)
![image](https://b1nzy.good-me.me/0d1ba5.png)

I'm in 40 guilds and with optional libraries installed. I'm in around 6-7 large servers.

**Comment by abalabahaha** [comment]
Guild count doesn't really affect memory usage. How many users in the user cache for each of these accounts/libs? And how many Members per guild?

**Comment by TTtie** [comment]
Around 51K users for my account. Both screenshots are with Eris.

**Comment by TTtie** [comment]
getAllUsers is true here.

**Comment by macdja38** [comment]
Can you use the chrome inspector to get a memory dump that shows what's using all the memory?

My bot uses around 250-500MB when on 1.8k guilds (and that includes music and all that), that's not a user bot though.

**Comment by LJNeon** [comment]
Sadly I don't have access to the chrome inspector.  But I just tested again, when I set `getAllUsers: true` the user bot actually gets killed by my IDE for using more memory than I'm allowed to use. (512MB)  When it's not set the bot takes ~40 seconds to ready up and uses just over 500MB at `ready`, falling down to ~350MB after another ~40 seconds.  The amount of cached users starts at around ~450,000 and climbs at 100-1000/s with a minimal effect RAM used. (the RAM started climbing again at a rate of approximately 5MB RAM / 3000 cached users)

After `ready` event fired:
![screenshot 2017-07-19 at 9 50 15 am](https://user-images.githubusercontent.com/23249107/28379365-370010be-6c68-11e7-82d4-b2220a79912e.png)
RAM and CPU usage for the whole time:
![screenshot 2017-07-19 at 10 01 12 am](https://user-images.githubusercontent.com/23249107/28379628-3ae06f52-6c69-11e7-9dcd-7848d0d3c9b6.png)
Taken at the same time as the second screenshot:
![screenshot 2017-07-19 at 10 01 43 am](https://user-images.githubusercontent.com/23249107/28379664-53e4b1c0-6c69-11e7-8c66-08f14b9e1802.png)

**Comment by abalabahaha** [comment]
Also, ask John to check discord.js memory usage after ~30 seconds. Eris does guild sync (online member download) before emitting the `ready` event, whereas discord.js does this after `ready`, so that "20MB" is missing a couple hundred thousand Member objects.

**Comment by RealBlazeIt** [comment]
Gradually rises and stops at around 80 MB, when testing the `discord.js` basic example. Using the basic `eris` example, I consistently get to 3-4 times more than with `discord.js`. Disabling events and setting the message cache limit to 0 didn't seem to help.

**Comment by abalabahaha** [comment]
How are you all measuring this? If you're not using `process.memoryUsage().heapUsed`, can you monitor that?

**Comment by Zaruike** [comment]
@abalabahaha  I think that eris has a memory leak my bot turns under eris for about 4 months since I made the update in the last version the bot made 600MB from the start and stays there at times makes falls at 500MB But no more ... the better it dropped and 100MB for 1 minute
![image](https://user-images.githubusercontent.com/23628673/29282483-4a11c66e-8123-11e7-87d8-4b4819b27779.png)

**Comment by abalabahaha** [comment]
@Jorisvideo try running a barebones script (only eris, Client instance, basic logging, and nothing else) and tell me what the results are

**Comment by Zaruike** [comment]
@abalabahaha 
Sorry not to have answered before ...


I just run eris with a simple client test with the same type of debug without anything else.

The test gives me about startup 350 MB and after 8 hours of launch we are as 250MB of ram used users are not cached so is this logical?

**Comment by abalabahaha** [comment]
@Jorisvideo well during ready Discord sends a ton of compressed data that the lib has to unpack and store in memory, so it should be using more RAM than normal for the first few minutes. It should decrease after a few minutes though, try checking then.

**Comment by melmsie** [comment]
@RealBlazeIt I moved a 20k server bot from discord.js to Eris without changing how any of the code works, and I went from 6-8gb of usage and consistently rising to 1-2gb of usage in Eris and it staying steady around 2gb. (yes I realize that its not a selfbot, but it shouldn't make a difference what the use case is}

**Comment by abalabahaha** [comment]
Still unable to find conclusive evidence that selfbot performance is significantly different from that of a similar bot or lib (equivalent message cache limit, user count, garbage collection timing, etc.). Feel free to comment if someone finds new stuff.
