### ISSUE TITLE
Documentation for GuildAuditLogEntry is contradictory

### ISSUE THREAD

**Issue by Ratismal** [abalabahaha/eris#272]
Just reporting an inconsistency in the docs 
![whao](https://everyone.needs-to-s.top/f34de5.png)
<http://eris.tachibana.erendale.abal.moe/Eris/docs/GuildAuditLogEntry>

The first line says that it returns an ID. The subsequent lines say that it *doesn't* return an ID. Just a bit of a contradiction.

Additionally:
![whao](https://requires.discord.gold/0b1ad8.png)

It refers to Constants.AuditLogActions without providing a link. The `Reference` page does not contain these values.

**Comment by LJNeon** [comment]
This is already fixed in dev, that was one of the typos I corrected.
https://github.com/abalabahaha/eris/blob/dev/lib/structures/GuildAuditLogEntry.js#L14

**Comment by LJNeon** [comment]
Although I was unable to edit the reference page, so abal might find this a useful reminder.

**Comment by macdja38** [comment]
Maybe it would make sense if it returned an id if the item was not cached?

**Comment by LJNeon** [comment]
I remember suggesting that and abal said something about not all the possible returns having an ID.

**Comment by abalabahaha** [comment]
Whoops yeah, haven't built the docs for a while, but I do need to get that on the reference page.

@macdja38 you're looking for `.targetID`
