### ISSUE TITLE
Eris doesn't automatically use Bluebird.

### ISSUE THREAD

**Issue by LJNeon** [abalabahaha/eris#279]
"install them in the same directory as Eris, and Eris will automatically use them" - the docs

Yet when I search for "bluebird" in this repository I get no results.  So are the docs misleading or did someone forget to use bluebird?
[![the docs](https://user-images.githubusercontent.com/23249107/29385974-b1cce43e-828e-11e7-8fd7-96237ee95077.png)](https://abal.moe/Eris/docs/getting-started)
![the search results](https://user-images.githubusercontent.com/23249107/29386027-ee74e760-828e-11e7-8721-ffd7a5ce5275.png)

**Comment by abalabahaha** [comment]
Yeah, whoops, the library doesn't do this anymore (since some people were complaining). If you want Eris to use Bluebird, you should set global.Promise. I'll remove Bluebird from the docs.
