### ISSUE TITLE
channel on message is always a normal channel in typings

### ISSUE THREAD

**Issue by na-2n** [abalabahaha/eris#284]
![](https://cat.girlsare.life/0985b7.png)
Should be
![](https://cat.girlsare.life/0d2eb0.png)

**Comment by abalabahaha** [comment]
mfw there's no label for this

**Comment by aurieh** [comment]
#285 fixed this 👀

**Comment by abalabahaha** [comment]
Pending master merge

**Comment by aurieh** [comment]
ah fair point
