### ISSUE TITLE
result of toJSON on a guild methods still contains circular references

### ISSUE THREAD

**Issue by cryptiklemur** [abalabahaha/eris#288]
Can test with: `console.log(JSON.stringify(client.guilds.get(81384788765712384).toJSON()));`

**Comment by macdja38** [comment]
The toJSON method on the guild object relies on the value of every key either being stringifyable or containing a toJSON method. It seems that a bunch of objects contained in the guild object do not have valid toJSON methods such as the shard class, the client class, the requestHandler class and others.

At the moment if you absolutely need a quick patch you may want to try something like this https://github.com/macdja38/pvpcraft/blob/master/PvPCraft.js#L18-L47

**Comment by LJNeon** [comment]
How I currently handle this is adding the toString property as toJSON and inspect properties as well:
```
Object.keys(Eris).filter(prop => Eris.hasOwnProperty(prop) && typeof Eris[prop] === "function").forEach(prop => {
	Eris[prop].prototype.toJSON = Eris.Base.prototype.toString;
	Eris[prop].prototype.inspect = Eris.Base.prototype.toString;
});
```
but I think `Base.toString()` is only on dev atm.

**Comment by abalabahaha** [comment]
That _should_ fix it, can someone verify?
