### ISSUE TITLE
Clean up REST errors

### ISSUE THREAD

**Issue by PassTheMayo** [abalabahaha/eris#329]
Hello. This really isn't an urgent thing, but I want to suggest something. I have been getting tons of 403 errors (no permission to send messages) a lot. When I was with Discord.js, there was a way to properly check the error code or message. With Eris, it seems a bit more *finicky*. Here is an example of a 403 error in Eris:
![image](https://user-images.githubusercontent.com/16949253/32711425-6f8eea16-c804-11e7-9bd6-bffe8218fd97.png)
As you can see here, there is also a problem with this. I am using `process.on("unhandledRejection")` but part of the error seems to bypass it, including a duplicate of it goes through the event handler. The red part at the top is the part that bypassed the `unhandledRejection`, while the green at the bottom means it was properly logged using the event. I believe that this is an error with the lib. Here is my code:
```js
process.on("unhandledRejection", (error) => {
	console.log(error);
});
```
With the fix to the duplicate errors, I also wish to request that the errors get some sort of fix-up, so that it can be better parsed by the bot. For example, here is an error that would be easily be parsable by the bot, and could be handled properly:
```js
{ Error: 50013 Missing Permissions
    at repl:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8) type: 'DiscordAPI', code: 50013, name: 'Missing permissions' }
```
That was just an example that I created within the Node.js REPL client. I believe that the errors could be cleaned up easily, and wouldn't be too hard to do. Thanks.

**Comment by abalabahaha** [comment]
Your "duplicate error" appears because you aren't handling the rejection of the Promise returned by the `createMessage()` call, and NodeJS 8+ is telling you so, as you can see on the first line of the screenshot you posted. Adding a standard Promise `.catch(func)` should fix that.

Regarding formatting, the error you posted is technically in that format, but it seems adding the response as a property (`resp`) of the error is confusing the NodeJS inspector. For the error you screenshotted, `error.message` would return a string that looks like (in human form):
```
Error: 403 FORBIDDEN on POST /channels/285084336225779722/messages
{"code": 50013, "message": "Missing Permissions"}
```
`error.stack` would return a string that looks like (in human form):
```
Error: 403 FORBIDDEN on POST /channels/285084336225779722/messages
{"code": 50013, "message": "Missing Permissions"}
    at Gunzip._respStream.on.once (/root/bots/guess-that/number/src/node_modules/eris/lib/rest/RequestHandler.js:260:39)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    ... you get the idea
```
Both `message` and `stack` are properties of normal `Error`s, and the logged object is still an `Error` like the sample repl you did. I'll see what I can do about hiding the `error.req` and `error.resp`.

**Comment by PassTheMayo** [comment]
@abalabahaha Is it possible to let the `process.on("unhandledRejection")` take care of all the uncaught promise rejections instead of `.catch()`ing each one? That is what I wanted to do, and it *sorta* works.

**Comment by cryptiklemur** [comment]
That is a really bad idea. You lose your stack trace and any context of the exception.

**Comment by abalabahaha** [comment]
Along with ^, unhandled rejections are NodeJS behavior and out of my control. I'm not aware of a properly handled rejection emitting a duplicate error, so try that.

**Comment by macdja38** [comment]
This issue does bring up an interesting point, it would be cool to see something like https://nodejs.org/en/blog/release/v8.0.0/#static-error-codes but for Eris error codes. It would be cool to see all the possible errors a method could reject the promise with under each method in eris. (It would also be a ton of work).

**Comment by PassTheMayo** [comment]
@macdja38 I agree, there need to be a better way to parse errors, and easily view what the problem is with `.message` or `.code`, instead of trying to look through raw data.

**Comment by LJNeon** [comment]
AFAIK you can already use `.message` and `.code`, here's a [list](https://discordapp.com/developers/docs/topics/response-codes#json-error-response) of potential messages/codes for errors.
