### ISSUE TITLE
implement new game types

### ISSUE THREAD

**Issue by lewisakura** [abalabahaha/eris#330]
discord recently released "Watching" and "Listening To" game types, possibly one more. is there a chance this could be implemented?

**Comment by LJNeon** [comment]
It's already implemented,
```js
Client.editStatus({name: "you sleep", type: 3});
```
for example

**Comment by LJNeon** [comment]
0 = Playing
1 = Streaming
2 = Listening to
3 = Watching

**Comment by lewisakura** [comment]
isn't listed in docs.

**Comment by Brayzure** [comment]
The docs have not been updated yet, since actual support is still in the dev branch afaik.

**Comment by lewisakura** [comment]
still provides confusion though. feels like they're not implemented.

**Comment by abalabahaha** [comment]
There’s nothing to implement, it’s just raw gateway data ¯\\\_(ツ)_/¯

I’ll add something to the docs
