### ISSUE TITLE
Check environment variables if no client params are passed

### ISSUE THREAD

**Issue by LJNeon** [abalabahaha/eris#332]
I've recently been toying around with [`pg`](https://www.npmjs.com/package/pg), and a cool feature from it is that you can [define environment variables and it'll automatically use them](https://node-postgres.com/features/connecting), allowing you to do stuff like
```js
this.client = new Eris();
```
and have it set itself up parameter free. Now I know this adds no real functionality because you can just do something like
```js
// environment variables must be strings so you'd have to parse it for the options
this.client = new Eris(process.env.ERIS_TOKEN, JSON.parse(process.env.ERIS_OPTIONS));
```
but imo it would be a nice addition to the lib. If the `process.env` variables don't exist it would function the same as before, meaning this has complete backwards compatibility. It's main use case would be for people using stuff like [Heroku](https://www.heroku.com) and [Cloud9](https://c9.io/?redirect=0).

Depending on feedback I'm fully willing to make a PR to add this.

**Comment by abalabahaha** [comment]
So after some discussion in Discord, the general consensus seems to be:

- It's not that hard to add an extra `process.env.SOMETHING` to your code
- This doesn't really belong in the library
- It's use cases are pretty niche and limited, and the cases you listed (Heroku/C9) both allow `process.env`
- A JSON-encoded environment variable for options is weird
