### ISSUE TITLE
member.ban(): Cannot read property 'shard' of null

### ISSUE THREAD

**Issue by PassTheMayo** [abalabahaha/eris#343]
Hello. I tried to use `member.ban()` but I received an error upon doing so. Here is the code I tried to use:
```js
bot.getRESTGuildMember(285084336225779722, 263474320133586946).then(member => {
    member.ban(0, "Example reason").then(() => {
        msg.channel.send("ban done");
    }).catch((error) => {
        msg.channel.createMessage("failed to ban");
        console.error(error);
    });
}).catch(console.error);
```

This is the error:
```js
TypeError: Cannot read property 'shard' of null
    at Member.ban (/Users/jacobgunther/Documents/Prisma/node_modules/eris/lib/structures/Member.js:184:27)
    at resolveMember.then (/Users/jacobgunther/Documents/Prisma/src/commands/ban.js:17:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I am running Eris `0.8.2`. Thank you!

**Comment by abalabahaha** [comment]
A stacktrace would be nice

**Comment by PassTheMayo** [comment]
@abalabahaha Check now, I have updated it. I had documented it improperly, so I was re-writing the issue so it was explained better.

**Comment by Thewsomeguy** [comment]
I took a look at Eris source code, it appears to come from that method passing a null guild to the member constructor https://github.com/abalabahaha/eris/blob/master/lib/Client.js#L1880

Then `member.ban()` depends on the guild, which is null https://github.com/abalabahaha/eris/blob/master/lib/structures/Member.js#L184

**Comment by PassTheMayo** [comment]
@Thewsomeguy Is that a problem with my code or the Eris library?

**Comment by abalabahaha** [comment]
REST methods assume you don't have anything cached, so stuff like `.guild` is undefined since that's not returned in the REST response. So the shortcut methods won't work. Use the `bot.banGuildMember()` stuff.

**Comment by PassTheMayo** [comment]
Ok

**Comment by macdja38** [comment]
Just a note to anyone that stumbles accross this in the future, please wrap your guild and member ids in "", js numbers don't have enough precision to hold discord ids so we use strings instead.

**Comment by PassTheMayo** [comment]
@macdja38 I actually used a variable in my code which was a string, but I just typed out the value to make it easier, but I forgot the quotes.
