### ISSUE TITLE
GuildChannel.nsfw property is not nullable in docs

### ISSUE THREAD

**Issue by macdja38** [abalabahaha/eris#347]
When a channel is not nsfw the nsfw property is undefined instead of false, as the docs would leave you to believe. 

docs: https://abal.moe/Eris/docs/GuildChannel

code:
https://github.com/abalabahaha/eris/blob/master/lib/structures/GuildChannel.js#L34
(I assume discord does not include data.nsfw if the channel is not nsfw)

**Comment by macdja38** [comment]
Possible fix https://github.com/abalabahaha/eris/pull/348

Alternatively docs could be updated to reflect behavior.

**Comment by abalabahaha** [comment]
Let's go with docs then
