### ISSUE TITLE
createInvite options missing unique in docs

### ISSUE THREAD

**Issue by SomeoneCares11** [abalabahaha/eris#349]
Hi,

i saw that invite link doesn't change when i create a new one, thought there a problem
after checking to discord api i found that there `unique` option
https://discordapp.com/developers/docs/resources/channel#create-channel-invite

its working on Eris but need to add to the docs

https://abal.moe/Eris/docs/TextChannel#function-createInvite
https://abal.moe/Eris/docs/VoiceChannel#function-createInvite
= Arch.

**Comment by abalabahaha** [comment]
Oh wait, it's in the [`Client.createChannelInvite()` function docs](https://abal.moe/Eris/docs/Client#function-createChannelInvite). Guess someone forgot to copy that over...
