### ISSUE TITLE
A way to determine how many guilds/users there are in a shard

### ISSUE THREAD

**Issue by PassTheMayo** [abalabahaha/eris#369]
Hello. I am using Eris in all of my bots, and I wanted to make a shards command. This shards command will display the guild count & user count per shard. I was wondering, why isn't there a way to tell how many guilds or users there are in a specific shard? I've had to use some very funky makeshift code in order to get it to work, like this:
```js
Object.keys(bot.guildShardMap).filter((id) => bot.guildShardMap[id] === s.id).length.toLocaleString()
```
... and this too:
```js
new Set([].concat.apply([], Object.keys(bot.guildShardMap).map((id) => bot.guilds.get(id).members.map((m) => m.id)))).size.toLocaleString()
```
I know it's not the best way, but I believe it's the only way. Can the Eris lib please provide an easier way to get these values? Thanks.

Edit: Just realized my second code posted doesn't even work, but you get the point ;)

**Comment by SomeoneCares11** [comment]
bot.guilds.size = how many guilds
bot.users.size = how many users

**Comment by abalabahaha** [comment]
Keeping track of shard object ownership would add quite a bit of overhead for a dumb little stats command that most lib users won't ever use. Just do the filter like you're doing now.

@SomeoneCares11 he said per-shard, not per-client.
