### ISSUE TITLE
How do you set a bot’s status using Eris?

### ISSUE THREAD

**Issue by ShearHost** [abalabahaha/eris#384]
I’ve tried multiple things like bot.editStatus(‘online’ , ‘game here’), as it said on the docs, so can anyone please help me?

**Comment by abalabahaha** [comment]
As the docs actually say, `game` is supposed to be an object, and `game.name` can be a string, which is probably what you're going for. So probably more like:
```
bot.editStatus("online", {
  name: ...
})
```

In the future, please use the Discord channel in the README for support questions.

**Comment by ShearHost** [comment]
Thanks :)
