### ISSUE TITLE
purgeChannel improperly handles non-whole numbers

### ISSUE THREAD

**Issue by brussell98** [abalabahaha/eris#391]
Passing a float to `Client#purgeChannel` (such as 1.4 in my case) causes the function to loop forever, deleting all messages until some other condition forces it to stop. This can be fixed easily by changing `limit === 0` to `limit <= 0`, or rounding limit.

**Comment by eritbh** [comment]
shouldn't this be closed now? looks like GitHub didn't pick up the "fix #391" in the commit above

**Comment by abalabahaha** [comment]
GitHub only listens for keywords in master branch.

I should probably package a release with this.
