### ISSUE TITLE
[Feature] Automatically suppress configurable Discord API errors by code

### ISSUE THREAD

**Issue by PassTheMayo** [abalabahaha/eris#392]
Just recently my polyfill for automatically suppressing 50013 `Missing permissions` errors using `process.on('unhandledRejection')` seems to no longer be functional. After a long (and arguable) chat in the Discord API server, I have came up with a solution that can (and should) be added. In the client options constructor, there should be an array that you can set that you can fill with error codes to suppress from the Discord API. So for example, here is my code:

```js
const Eris = require('eris');
const bot = new Eris('abc123', {
    suppressErrors: [ 50006, 50007, 50013 ]
});
```

I think that this would help out a lot of developers to reduce the amount of clutter in the console and make it easier to sort through other errors. I'm not sure how exactly this would work on the programmatic side, but I'm guessing it can be done. Thanks!

**Comment by Brayzure** [comment]
I personally disagree with the addition of this feature. Errors are emitted for a reason, and you're better off handling them properly as opposed to just ignoring them. If you really want to ignore them, it's relatively easy to wrap whatever function you want to ignore the errors from.

**Comment by PassTheMayo** [comment]
Obviously chat seems to be very biased because they prefer DIY over ease of use.

![image](https://user-images.githubusercontent.com/16949253/40595945-619e84b4-61fd-11e8-9968-8c84459e6835.png)

**Comment by LJNeon** [comment]
I'm also against this. As the aforementioned chat said it'd be bad practice to rely on this, and it's really not hard to implement yourself at all. Eris has never been a lib that spoonfeeds or does all the work for you. A feature like this doesn't belong in the lib.

To continue said conversation that you just gave up on:
If you insist on doing it with `process.on('unhandledRejection')` regardless of our warnings of bad practice, [the only parameter to that event should be `error`](https://nodejs.org/api/process.html#process_event_uncaughtexception), remove the `reason` parameter and you should be fine.

If you value quality code over your own opinions you should refer to the conversation in there for several better alternatives.

**Comment by LJNeon** [comment]
It's the lib itself that has DIY over ease of use bias. If you need to be spoonfed code and have everything done for you might I recommend d.js?

**Comment by Brayzure** [comment]
It's not a matter of DIY vs ease of use. It's a matter of encouraging bad practice. Handling errors yourself is exactly what you should be doing, all the time. Ideally, you shouldn't have to ever use `process.on("unhandledRejection")`.

**Comment by PassTheMayo** [comment]
Still not sure why people are getting so mad over this idea. I think it's a great idea, but some people disagree and feel like they need to tell me how it's "bad practice". Maybe I like it how *I* do it, and I don't always need to take suggestion from others. Abal should really just lock this until he replies. I'm just gonna lock it and abal can unlock when he gets an email or something.

**Comment by PassTheMayo** [comment]
Meh, turns out that doesn't lock it :(

**Comment by MoordMachineYT** [comment]
It’s not just bad practice, but also a bad idea for several methods. Almost every method responds with a promise, and they reject if they get an error. But if those errors were to be supressed like in your example, is the promise supposed to resolve with nothing? Or is it still gonna reject, leading to an unknown error? Either way, it’s not a good idea to implement.

**Comment by abalabahaha** [comment]
Unexpected errors should always be handled in some way: tell the user, log something, etc. Black-holing errors is indeed bad practice, irrelevant of "bias", and I'd rather not encourage that in the lib. If you're intentionally expecting something to result in random error(s) and want to ignore those, feel free to do that in a `.catch()` from your end. ~~Maybe I like it how I do it, and I don't always need to take suggestion from others.~~

Also, you should be handling Promise rejections, `unhandledRejection` should only be used for finding and handling Promises you missed.

Locking an issue solely because many people are disagreeing is also bad practice. Though if this becomes a flame war it will get locked.
