### ISSUE TITLE
Sending an embed in "messageUpdate" listener will fire the event again causing a loop.

### ISSUE THREAD

**Issue by takase1121** [abalabahaha/eris#395]
When I try to send an embed in a "messageUpdate" listener, Client starts to fire the "messageUpdate" event non-stop, causing a loop and spammed my channel. Is this a bug related to eris?

**Comment by MoordMachineYT** [comment]
I’ve seen this problem in the d.js server, so I’d assume it’s a problem with the api. A message is sent and then edited to include the embed if I’m correct.

**Comment by takase1121** [comment]
I see. I will add a temporary solution to my code first, and see if this problem will be fix. Thanks!

**Comment by abalabahaha** [comment]
Yeah Discord has a bug_?_ where embeds you send still fire a `messageUpdate` for some reason. It would be wise for you to check for an actual change in message content
