### ISSUE TITLE
Case-Insensitive Commands

### ISSUE THREAD

**Issue by TehSeph** [abalabahaha/eris#4]
Would be nice to see support for case-insensitive commands such as `!command`, `!Command`, `!COMMAND`, etc. maybe by default or via a flag under the command options param.

**Comment by cernodile** [comment]
I believe it's easy to make, then again I haven't really looked into buildup of the system that much. From what I know `toLowerCase()` should do the thing.

**Comment by TehSeph** [comment]
`toLowerCase()` would be exactly how I would do it too. It only needs to be done in two places: one on the input from `registerCommand()` and another on the parser after `args.shift()`

**Comment by abalabahaha** [comment]
Done in #dev, pending merge to master (yes this is late)
