### ISSUE TITLE
msg.member is null when message in server?

### ISSUE THREAD

**Issue by lewisakura** [abalabahaha/eris#403]
using messageCreate to get the `msg` object, but `msg.member` is null until i assign the user a role. using latest Eris @ npm

**Comment by abalabahaha** [comment]
Sounds like the user is invisible. Eris hasn't been updated to handle the extra data Discord sends with lazy guilds yet, so invisible members that aren't cached (`getAllUsers: false`) won't populate `msg.member`.

**Comment by lewisakura** [comment]
Ah, makes sense. Have any idea when you will update for lazy loading?

**Comment by mets11rap** [comment]
Wish lazy loading were gone tbh

**Comment by mets11rap** [comment]
I know. Just in general

**Comment by LewisTehMinerz** [comment]
I guess they could send user ID/username pairs initially but nothing else until it's needed.
