### ISSUE TITLE
purgeChannel ignores Webhook Messages

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#405]
there are no errors, it deletes everything below a webhook message, and ignores everything above it.

**Comment by LJNeon** [comment]
there's a lot of reasons why it would stop at that message, can you make a small code sample to reproduce this behavior?

**Comment by ghost** [comment]
```js
bot.on("messageCreate", (msg) => { // When a message is created
    if(msg.content === "\\|clear") { 
        bot.purgeChannel(msg.channel.id, -1);
        bot.createMessage(msg.channel.id, "["+Date()+"] "+msg.author.id+" "+msg.author.username+"#"+msg.author.discriminator+" "+msg.author.mention+" cleared the channel "+msg.channel.mention+" with id "+msg.channel.id);
        console.log("["+Date()+"] "+msg.author.id+" "+msg.author.username+"#"+msg.author.discriminator+" "+msg.author.mention+" cleared the channel "+msg.channel.name+" with id "+msg.channel.id);
    }
});
```

**Comment by LJNeon** [comment]
Just ran that exact code and it deleted several webhook messages perfectly fine.

**Comment by LJNeon** [comment]
That method uses bulk delete, which is unable to delete messages older than 2 weeks. Are you sure that isn't your problem?

**Comment by LJNeon** [comment]
Also the preferred way to delete every message in a channel is to delete and recreate the channel itself, this is bad practice.

**Comment by ghost** [comment]
oh, sorry for the issue, they are older than 2 weeks
