### ISSUE TITLE
Send `Buffer` as attachment in `createMessage()`

### ISSUE THREAD

**Issue by takase1121** [abalabahaha/eris#413]
Is this possible instead of sending strings? Because I'm afraid that the string will break the binary contents, but converting it into base64 and send it will increase size.

**Comment by exoRift** [comment]
https://i.imgur.com/qWFSSmg.png ?

**Comment by takase1121** [comment]
![image](https://user-images.githubusercontent.com/20792268/43990948-5355f80a-9d95-11e8-899e-a58520f91e97.png)
 ^ the picture above is `TextChannel#createMessage()`. Is this a doc error because I think that they all should work the same.

**Comment by abalabahaha** [comment]
Whoops, missed a couple of those. Buffer is right for all of them, should be fixed now.
