### ISSUE TITLE
SUGGESTION: awaitMessage()

### ISSUE THREAD

**Issue by exoRift** [abalabahaha/eris#415]
I was talking with my friend earlier and he was using code with Discord.js's `awaitMessage` function. I looked in the Eris docs and discovered we don't have anything like that. It would be very useful for my code, and I assume others and makes more sense logic wise to use it instead of an else if statement or something.

`Channel.awaitMessage(userID[, msgContent])`
Returns: Promise (On resolve: The message object)
Will resolve when `userID` sends something in `Channel`
If `msgContent` is specified, only resolve when `Message.content === msgContent`
**Maybe**: If the promise isn't resolved after X amount of time, reject?

**Comment by ghost** [comment]
make own implementation at your message handling or use [eris-additions](https://github.com/minemidnight/eris-additions)

**Comment by exoRift** [comment]
I'm saying it should be added to the official

**Comment by exoRift** [comment]
Closed after explanation of why not in Discord
