### ISSUE TITLE
RTP Header Extension parsing is broken

### ISSUE THREAD

**Issue by Yahweasel** [abalabahaha/eris#416]
Similarly to the spate last year of RTP header data getting mixed in, our good friends at Discord are sending more garbage along with Opus data. I ( https://bitbucket.org/Yahweasel/craig/src ) started receiving data that had bizarre buzzing in it today, and it turns out that some set of Opus packets are being prefixed with 0x90 0x00. This *is* a valid Opus header, but for a 10ms data packet, so it's unlikely to be correct coming from Discord, and it decoded to nasty buzzing. I started stripping it off, and the following data is valid Opus that sounds right.

Since the data comes to me out of Eris, I don't know if it's already had some RTP header stripped off (perhaps incorrectly?), or if this is an entirely new issue. It could also be transient of course. It seems to be happening with relative frequency with data from all clients I've tested: At least Firefox, the desktop client on Linux, and the Android client, as well as some Windows clients used by Craig users.

**Comment by GregorR** [comment]
FYI, the tracking and resolution for JDA, used by the only other public recording bot:

https://github.com/DV8FromTheWorld/JDA/issues/763

https://github.com/DV8FromTheWorld/JDA/pull/764

They seem to claim (in 763) that it was resolved in RTP header handling.

**Comment by Yahweasel** [comment]
FYI, the tracking and resolution for JDA, used by the only other public recording bot:

DV8FromTheWorld/JDA#763

DV8FromTheWorld/JDA#764

They seem to claim (in 763) that it was resolved in RTP header handling.
