### ISSUE TITLE
Guild property of member object is null when member object is obtained through the REST API

### ISSUE THREAD

**Issue by Santhosh-Annamalai** [abalabahaha/eris#418]
Whenever I try to obtain the member object of a user via the REST API, the guild property of the member object is null.
![image](https://user-images.githubusercontent.com/34129975/44950144-f62aed00-ae5d-11e8-9d41-8ebb7cdac6ee.png)
This doesn't seem to be the case when I obtained the member object from a message object.
![image](https://user-images.githubusercontent.com/34129975/44950148-270b2200-ae5e-11e8-861c-42d25bf1ef74.png)
This leads to an error whenever I try to obtain the permissions of a user from a member object obtained via the REST API for example.
![image](https://user-images.githubusercontent.com/34129975/44950136-cf6cb680-ae5d-11e8-802b-3cd9005c1129.png)
I'm not sure if the guild property is meant to be null or not. If so, I guess replacing null with the guild object would be nice. Relevant line [here](https://github.com/abalabahaha/eris/blob/86fb1fc3753bdf1910796cd75c66845f2ca0fe38/lib/Client.js#L1899).

**Comment by ghost** [comment]
It's intentional as discord doesn’t returns guild data when fetching member so there is no way to know which guild to assign but lib could always take the guild snowflake and use it to get guild from cache

Right now you can either use `.fetchAllMembers()` method on guild
Or modify local copy Eris to get expected result

**Comment by Santhosh-Annamalai** [comment]
I see. Thanks for the clarification! I just wanted to clear my doubt on this issue which I cleared now.

**Comment by abalabahaha** [comment]
Not entirely correct, we should at least attempt to fill the guild from cache
