### ISSUE TITLE
URI malformed error is thrown when Audit-Log reasons include a percent sign

### ISSUE THREAD

**Issue by Santhosh-Annamalai** [abalabahaha/eris#420]
The aforementioned error is thrown for guild related requests like `kickGuildMember` and `addGuildMemberRole` where Audit-Log reason is passed in the `X-Audit-Log-Reason` header. It doesn't occur for requests where the reason is passed as the query param like `banGuildMember` for example. It seems like the decodeURI check in [this](https://github.com/abalabahaha/eris/blob/master/lib/rest/RequestHandler.js#L87) line is causing the issue. Here is a screenshot of the error which I got when I tried to add a role to a member with `%` as the reason.

![image](https://user-images.githubusercontent.com/34129975/45713207-05bf6b00-bbac-11e8-97ab-389f0cec33c9.png)

As Discord supports adding special characters like `%` in its audit-log reason when a member is kicked manually, I would expect the same for API related requests. I tried removing that decodeURI check after which I didn't get that error and that member was successfully kicked out. So I guess that check could be removed if that's a viable solution. Or any other alternative solution would also be welcomed by me! 😄

**Comment by AlekEagle** [comment]
One reason this could be caused is how it is sending the request, to my knowledge Discord is effectively one huge REST API handler, and percent signs in internet terms mean encode the next two hexadecimal numbers as x symbol, and it is returning malformed URI because it doesn't have anything to encode. (May not be correct but this is my theory.)

**Comment by MoordMachineYT** [comment]
No, that's completely wrong. The reason it failed, was because the client was trying to *decode* a string. And if you were to encode a percent sign `%25` would be returned. So that's also no issue. And regardless, this issue has (likely) been fixed in #426.

**Comment by AlekEagle** [comment]
Like I said, I may have been completely wrong, but thank you for assuring me that I was wrong.
