### ISSUE TITLE
Eris "Already Encoding" longer than actually encoding.

### ISSUE THREAD

**Issue by PikaDude** [abalabahaha/eris#446]
Hi I just wanted to say that I'm not very good at writing issues, but here goes.

If you play a file from a url in Eris using `voiceConnection.play()`, Eris sets `voiceConnection.playing` to `true` for much longer (usually 5 to 10 seconds longer) than it is actually playing the file and it will also not let you try to play a file during this time as it'll return the error "Already encoding" when it is not actually playing anything or doing anything. I've actually managed to narrow down the issue to de56b533242b28bd0f703d652d0ff1da16562dde, this commit first introduced this issue and I have no idea why or how, just that it does.

**Comment by abalabahaha** [comment]
Fixed by #417, pending master release.
