### ISSUE TITLE
Better presence support/mobile indicators

### ISSUE THREAD

**Issue by Cynosphere** [abalabahaha/eris#453]
Instead of having presence split between multiple objects, it'd be better to have it as one with sub-objects, and with the "raw" data.

This would also enable support for mobile indicators automatically.

**Comment by Brayzure** [comment]
Not sure what you mean, are you referring to what I'm trying to do with #449 ?

**Comment by abalabahaha** [comment]
Still somewhat confused on what "presence split between multiple objects" means, can you elaborate?

**Comment by Cynosphere** [comment]
In the current member object, the status and game are split between two objects whereas in the actual websocket they're one object

**Comment by abalabahaha** [comment]
Oh you mean the presence update data. The structure of those didn't change for a long time, but they've gotten a couple new fields recently, so it might be worth revisiting how we store these. Though we'd have to filter out a lot of non-presence fields like roles and nicks.

Anyway, #449 merged, mobile indicators soon:tm:
