### ISSUE TITLE
Documentation Error in guild.getBans

### ISSUE THREAD

**Issue by Ryu945** [abalabahaha/eris#454]
The documents claim guild.getBans() gives an array of user objects.  It really gives an array of ban objects.

Also, I don't see the Ban object in the list of classes.  There are things like channel objects and message objects but there is no mention of the ban object.

**Comment by Brayzure** [comment]
The docs do need to be updated to reflect that. The reason why the ban object is not documented is because there isn't a class for it. There's no class probably because the ban object is so simplistic (just a user and a reason), and because it's used in exactly two endpoints iirc.
