### ISSUE TITLE
again the reactions wont work

### ISSUE THREAD

**Issue by MeetPing** [abalabahaha/eris#463]
it is because its outdated
BTW IM BANNED FROM THE DISCORD

**Comment by MeetPing** [comment]
@ownerDUUDUUDU

**Comment by abalabahaha** [comment]
Yeah, I see that you were banned for shitposting/spam. Making un-descriptive issues ("reactions wont work" is uninformative and nobody can help you), asking for people to spoonfeed you code, and random un-formatted GitHub/Discord messages that show no effort to be polite or respectful are also not helping your case. Sorry, please find another library to use.
