### ISSUE TITLE
Invalid converter command

### ISSUE THREAD

**Issue by SoraKatadzuma** [abalabahaha/eris#470]
I've been trying to play audio files made by a text to speech engine. The audio files are `.wav` format and they are playable. However, every time I try to play *any* audio file, regardless of the correct file path, I get the following error:
```
Error: Invalid converter command
    at new module.exports (/root/hestia/node_modules/eris/lib/voice/streams/FFmpegPCMTransformer.js:7:15)
    at Piper.encode (/root/hestia/node_modules/eris/lib/voice/Piper.js:143:52)
    at VoiceConnection.play (/root/hestia/node_modules/eris/lib/voice/VoiceConnection.js:451:24)
...
```

**Comment by eritbh** [comment]
Do you have `ffmpeg` installed and in your PATH?

You should join the Discord server listed in the repo's readme for support questions; GitHub issues are mostly for lib code changes/etc.

**Comment by SoraKatadzuma** [comment]
`ffmpeg` was not installed ;-;
Sorry for the waste of time, though I'd like to say it wasn't in the documentation that I needed to have it, it'd been nice to know back then than now.
