### ISSUE TITLE
Help with editPermission

### ISSUE THREAD

**Issue by audiodk** [abalabahaha/eris#478]
Trying to make a lock channel command.  `editPermission` keeps throwing me an error though.
`TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters`

Is this the correct way to set up?

`message.channel.editPermission({
            overwriteID: everyone.id,
            allow: 1024,
            deny: 2048,
            type: 'role',
            reason: reason
        });`

**Comment by abalabahaha** [comment]
No, the function signature is `editPermission(overwriteID, allow, deny, type, reason)`. Each argument needs to be a function argument, not grouped together as object properties.

Please use the Discord channel for support questions in the future.
