### ISSUE TITLE
getUserProfile & getSelfConnections returning promise<pending>

### ISSUE THREAD

**Issue by luandunas** [abalabahaha/eris#481]
On description of getUserProfile, the correct is return `promise<object>`, but is returning `promise<pending>`.

`bot.getUserProfile(UserID);` same thing for `bot.getSelfConnections();`

https://imgur.com/Z758Vud
https://imgur.com/pBuxZ3l

**Comment by LJNeon** [comment]
First off, obligatory don't use self-bots, you can and will get account banned from discord by doing so.
Second off, you seem to be lacking basic understanding in what a Promise is and how it works. Feel free to drop by the discord channel for help.

**Comment by luandunas** [comment]
Oh, sure.

**Comment by abalabahaha** [comment]
Clarification: logging a Promise usually prints `Promise<status of promise>`, like `pending`/`resolved`/`rejected`. Eris documentation contains the type of object the Promise will eventually resolve with. Do try reading up on the [JS Promise docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), and feel free to drop by the Discord channel in the README if you still have code questions.
