### ISSUE TITLE
index.d.ts is missing some properties on GamePresence and EmojiBase

### ISSUE THREAD

**Issue by oathompsonjones** [abalabahaha/eris#492]
Initially, the file has this `interface GamePresence { name: string; type?: number; url? string; }`
It is missing the following properties all of which I have encountered from the game being either Spotify or Visual Studio Code, there may also be more which I am not aware of which appear from other games.
`interface GamePresence {
    name: string;
    type?: number;
    url?: string;
    // missing properties
    timestamps?: {
        start: number,
        end?: number
    };
    sync_id?: string;
    state?: string;
    session_id?: string;
    party?: {
        id?: string;
    };
    id?: string;
    flags?: number;
    details?: string;
    created_at?: number;
    application_id?: string;
    assets?: {
        small_text?: string,
        small_image?: string,
        large_text?: string,
        large_image?: string
    }
}`

EmojiBase was also missing an `id` property, which is needed when handling the `onMessageReactionAdd` event.

**Comment by Rayan1159** [comment]
I suggest using discord.js instead.

**Comment by oathompsonjones** [comment]
@Rayan6666 if I wanted to use Discord.js, I wouldn't be leaving reports here. I find that Eris is a much better library for me to use, so I think I'll stick to using it.

**Comment by 0xN0x** [comment]
https://gist.github.com/AmazingArcher23/67f7366245d807e7cf410809eff859df

As you can see here, i think it's already possible, but not for bot account
It was 2 years ago then i'm not sure but why not

**Comment by oathompsonjones** [comment]
@Nundir That's not related to this issue. I was highlighting the fact that some properties are missing on the `type` `GamePresence` in the `index.d.ts` file. That link has got nothing to do with missing properties, or Eris at all for that matter.

**Comment by oathompsonjones** [comment]
I found another property to add. 
`platform?: string;`
I know that its value can be "xbox", I don't know of any others.

**Comment by eritbh** [comment]
I'm making a PR for this that includes the properties [documented by Discord](https://discordapp.com/developers/docs/topics/gateway#activity-object) for presence activity objects. I'll include a generic index signature so anything not documented is still accessible.

`EmojiBase` intentionally leaves off the `id` property, as it's added by the `Emoji` type which is what's used in the reaction events. If you're not getting an `id` property of emojis passed to reaction events, then your editor's autocomplete is bugged.
