### ISSUE TITLE
Already encoding/Unable to encode source Errors

### ISSUE THREAD

**Issue by attributeerror** [abalabahaha/eris#493]
I'm trying to recode my Discord bot in Eris (from JDA) and music is one of the main features of the bot. I've got it working for the most part but there's only one bug that I cannot find a fix for. Every time the queue reaches the 3rd song (no more, no less, **always** the 3rd song) in the queue, the bot will begin to error saying "Already Encoding" or "Unable to encode source" for the rest of the songs in the queue, and before long the queue is empty and the bot disconnects.

I have seen other issues that reference these errors, and it has something to do with the fact the bot is still 'playing' a file, despite me having stopped that stream before playing the next one in the queue. The only way I got these errors to stop, is to do: `if(connection.playing) connection.stopPlaying();` whenever a song ends before playing the next one - but again, it reaches the 3rd song and then just empties the rest of the queue.

I have tried using the dev version, but that just results in it erroring from the 2nd song onwards and doesn't fix anything. Any help will be appreciated!

**Comment by abalabahaha** [comment]
It's possible that you are registering the listener twice, using `.on()` instead of `.once()`, double-playing, etc... Can you join the Discord channel in the README?

**Comment by attributeerror** [comment]
I changed the two events to use `.once()` and it worked fine... don't know how I didn't even think of it myself, considering I looked at the example for playing files and saw that it was used there...
