### ISSUE TITLE
Unhandled message types.

### ISSUE THREAD

**Issue by AlekEagle** [abalabahaha/eris#496]
Recently the unhandled message types:
- type 8
- type 9
- type 10
- type 11

Have begun to cause errors, they are simply the nitro boost messages. Meaning, they are very similar to The guild member join messages. I know the messages no longer cause errors, only warnings, but it would be nice to have them handled. I'm not telling you that you should copy anything, but what I am saying is they are similar.

Documentation: https://discordapp.com/developers/docs/resources/channel#message-object-message-types

**Comment by ghost** [comment]
fixed in #495
