### ISSUE TITLE
When using VoiceChannel.join(), timeout causes uncatchable error and promise never resolves or rejects

### ISSUE THREAD

**Issue by mistval** [abalabahaha/eris#497]
I saw this happen several times last night while Discord was apparently misbehaving:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (/var/app/node_modules/ws/lib/websocket.js:217:14)
    at VoiceConnection.disconnect (/var/app/node_modules/eris/lib/voice/VoiceConnection.js:393:25)
    at Timeout.setTimeout [as _onTimeout] (/var/app/node_modules/eris/lib/voice/VoiceConnection.js:194:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Emitted 'error' event at:
    at VoiceConnection.disconnect (/var/app/node_modules/eris/lib/voice/VoiceConnection.js:395:22)
    at Timeout.setTimeout [as _onTimeout] (/var/app/node_modules/eris/lib/voice/VoiceConnection.js:194:22)
    [... lines matching original stack trace ...]
    at Timer.processTimers (timers.js:223:10)
```

This error is emitted before VoiceChannel.join() resolves or rejects, so there is no chance to register an error handler. If you use the process's uncaughtException event to catch it, the process of course doesn't crash, but VoiceChannel.join() never resolves or rejects.

To reproduce, first go to [VoiceConnection.js line 197](https://github.com/abalabahaha/eris/blob/master/lib/voice/VoiceConnection.js#L197) and set the timeout to something low (50 ms should do it, if you only get an UnhandledPromiseRejectionWarning, lower it more) in order to simulate a timeout. Then, the following code reproduces this:

```js
const Eris = require('eris');

const TOKEN = 'xxxxx';
const VOICE_CHANNEL_ID = 'yyyyy';

const client = new Eris(TOKEN);

client.on('ready', async () => {
  console.log('Client ready');

  const voiceChannel = client.guilds
    .map(g => g.channels.get(VOICE_CHANNEL_ID))
    .find(c => c);

  const voiceConnection = await voiceChannel.join();
  voiceConnection.on('error', () => {
    // This fails to catch the timeout because
    // voiceChannel.join() never resolves (never rejects either)
    console.log('Handled voice connection error');
  });
});

client.on('error', () => {
  console.log('Handled client error');
});

client.connect();
```
I would expect something inside of Eris to handle the error and make the `voiceChannel.join()` promise reject under these circumstances.

In production, I don't specify a timeout in the client options, so it's using the 30 second default. I've never had this happen other than last night several times over a period of ~1 hour when Discord status page was showing very high API response time (>900ms).

**Comment by eritbh** [comment]
Disconnections and errors should be handled here, for reference: https://github.com/abalabahaha/eris/blob/master/lib/voice/VoiceConnectionManager.js#L19-L35

Not sure what's causing that to go unhandled in your case.

**Comment by mistval** [comment]
I put in some breakpoints to take a closer look. It looks like those handlers you linked to never get registered in this case, because connection is undefined, so the guild is [added to pendingGuilds](https://github.com/abalabahaha/eris/blob/master/lib/voice/VoiceConnectionManager.js#L39-L50) and a new VoiceConnection is created down in [voiceServerUpdate()](https://github.com/abalabahaha/eris/blob/master/lib/voice/VoiceConnectionManager.js#L53). In that function, the new connection [has its "ready" and "disconnect" events listened to](https://github.com/abalabahaha/eris/blob/master/lib/voice/VoiceConnectionManager.js#L80-L104), but not its "error" event.

Indeed if I add an error handler in voiceServerUpdate() like this, it fixes the crash and replaces it with a promise rejection:

```js
const errorHandler = (err) => {
    const pendingGuild = this.pendingGuilds[data.guild_id];
    if (pendingGuild) {
        pendingGuild.rej(err);
    }
};

connection.once("ready", readyHandler).once("disconnect", disconnectHandler).once('error', errorHandler);
```

So maybe we need to be listening for errors there in voiceServerUpdate().

**Comment by ak-s** [comment]
In my case (0.10.0):
```js
eris.joinVoiceChannel(roomId)
.then(conn => {
	conn.on('error', err => {
		console.error(err);
		<...>
	});
	<...>
})
.catch(err => {
	console.error(err);
	<...>
});
```
and sometimes
```
> events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at WebSocket.ws.on (<...>/node_modules/eris/lib/voice/VoiceConnection.js:345:18)
    at WebSocket.emit (events.js:189:13)
    at ClientRequest.req.on (<...>/node_modules/ws/lib/websocket.js:568:15)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
