### ISSUE TITLE
Is it possible to see who removed a message?

### ISSUE THREAD

**Issue by OniHil** [abalabahaha/eris#517]
As far as I can see, the message object that gets sent when the event triggers doesn't show who deleted it.

**Comment by knht** [comment]
Hey there!

For general library questions we'd like you to rather directly ask them on the Discord channel linked on the README file or on the Eris docs website.

Coming back to your question, yes you're right, you can't check who's deleted the message without checking the audit logs.

If you have any further questions drop by in said Discord channel and we'll be sure to help out.
