### ISSUE TITLE
Zlib Error: unexpected end of file

### ISSUE THREAD

**Issue by briantanner** [abalabahaha/eris#521]
On occasion we encounter issues where either network or something is going wrong at Discord that results in shards crashing. I figured this is something that could probably be handled in eris to prevent crashes.

```
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
```

**Comment by abalabahaha** [comment]
Probably related to synchronization issues when using the built-in `zlib` module, since it doesn't have a suitable sync API. `pako` or `zlib-sync` is more stable when using compression. Might be time to stop falling back to `zlib`.

**Comment by abalabahaha** [comment]
6702773 drops `zlib` support. `pako` or `zlib-sync` provide better stability and efficiency.
