### ISSUE TITLE
Upgrade from Python 2.7

### ISSUE THREAD

**Issue by Owez** [abalabahaha/eris#534]
2.7's EOL is coming soon, should be upgraded to latest stable python (3.7.4 currently).

**Comment by ghost** [comment]
python version is dictated by https://github.com/nodejs/node-gyp#on-unix

**Comment by Owez** [comment]
Ah, gotcha.
That's a concern for the node contribs to fix I guess. Made an issue on the node-gyp ([here](https://github.com/nodejs/node-gyp/issues/1883)).

**Comment by kotx** [comment]
This has been fixed by node-gyp, should the README be updated as well?
