### ISSUE TITLE
dmOnly get's ignored when requirements.userIDs is used

### ISSUE THREAD

**Issue by sgywzy** [abalabahaha/eris#537]
When `dmOnly` is set to true and `requirements.userIDs` is used, `dmOnly` get's ignored and the bot respond in guild channels too.
```
bot.registerCommand('ping', 'pong',
  {
    dmOnly: true,
    requirements: {
      userIDs: ['userId1', 'userId2', 'userId3'],
    },
  });
```

**Comment by Geo1088** [comment]
The docs say these properties should be inside another object called `requrements`. This is user error. For further support, join the Discord linked in the project's README and we can assist a bit easier.

**Comment by eritbh** [comment]
Caused by this line of code: https://github.com/abalabahaha/eris/blob/master/lib/command/Command.js#L182

The `userIDs` check returns `true` before checking certain other requirements. This is a legit bug.
