### ISSUE TITLE
[docs] Update permissions in Reference

### ISSUE THREAD

**Issue by Cynosphere** [abalabahaha/eris#539]
Permissions like `viewAuditLogs` aren't listed in `Eris.Constants.Permissions` on the docs page

**Comment by spencer1573** [comment]
Hey! Looking to help out for hacktoberfest. I looked into updating the docs... and I couldn't really see where this repo's site was to edit it.  Let me know if I can help. thanks!

**Comment by eritbh** [comment]
@spencer1573 This info isn't in the repo anywhere and needs to be updated manually by abal. The majority of the documentation is generated from JSDoc comments in this repo, but some stuff is hardcoded like this.

**Comment by spencer1573** [comment]
oh ok thanks!
