### ISSUE TITLE
createChannel options object still accepts string for parentID

### ISSUE THREAD

**Issue by alex-taxiera** [abalabahaha/eris#554]
So, at some point in time `createChannel` took `parentID` as the fourth/fifth parameter. It was then extended to actually be an object of options, but the [functionality was left in place](https://github.com/abalabahaha/eris/blob/dev/lib/Client.js#L395) for "backwards compatibility".

Now it is entirely undocumented, but really I think it should be documented, marked deprecated, and the library should give a warning message if someone uses it this way.

Unless we're feeling frisky and want to just straight up remove it, that would be cool too.

**Comment by abalabahaha** [comment]
9622e6b marks it as deprecated and emits a warning. Typings still need to be updated

**Comment by abalabahaha** [comment]
1fe6dd2 got the typings
