### ISSUE TITLE
aborted event listener registration error

### ISSUE THREAD

**Issue by emarteca** [abalabahaha/eris#591]
Hi all, I've been working on a tool to identify instances of events registered to the wrong object in uses of some JavaScript event-driven APIs, as part of a research project.
The tool flagged [line 161](https://github.com/abalabahaha/eris/blob/master/lib/rest/RequestHandler.js#L161) in lib/rest/RequestHandler.js, on the registration of the “aborted” event.

The reason I believe this is indicative of an error is as follows (from looking at the [nodejs http API documentation](https://nodejs.org/api/http.html#http_http_request_options_callback)):
The req variable, as the return of the call to https.request on [line 146](https://github.com/abalabahaha/eris/blob/master/lib/rest/RequestHandler.js#L146), is an object of type http.ClientRequest. However, the “aborted” event is emitted on http.IncomingMessage, and not on http.ClientRequest.

Since there is a registration of a listener for “abort” [right before](https://github.com/abalabahaha/eris/blob/master/lib/rest/RequestHandler.js#L156) that for “aborted”, my guess is that the listener for “aborted” should just be removed.

Thanks!

**Comment by abalabahaha** [comment]
Interesting research! This seems to be a side-effect of `aborted` being _mis?_-documented as emitted by both `ClientRequest` and `IncomingMessage` in [Node 4's docs](https://nodejs.org/docs/latest-v4.x/api/http.html#http_event_abort) (nodejs/node#​10787 maybe?), which is about when I wrote this code.

**Comment by emarteca** [comment]
Interesting, I didn't know it was in the old docs! Thanks for the speedy response, and for letting me know! :)

Would you like me to submit a PR, removing the `aborted` listener?

**Comment by abalabahaha** [comment]
Whoops, been a little busy. Decided to move it to the `IncomingMessage`, but thanks for your help!
