### ISSUE TITLE
Voice UDP connection isn't being setup properly (IP discovery uses wrong encoding)

### ISSUE THREAD

**Issue by waynegerard** [abalabahaha/eris#592]
Even though the documentation states:

> To retrieve your external IP and port, send a 70-byte packet with empty data past the 4-byte ssrc. The server will respond back with another 70-byte packet, this time with a NULL-terminated string of the IP, with the port encoded in a **little endian** unsigned short stored in the last two bytes of the packet.

This is incorrect, it's **big endian**. 

Other libraries have implemented similar fixes, e.g. https://github.com/bwmarrin/discordgo/issues/668

**Comment by waynegerard** [comment]
I've confirmed that this fixes the issue (please ignore any syntax/etc. errors, this is just meant to be a pared down version of the relevant code in voiceConnection.js):

Little Endian: https://gist.github.com/waynegerard/0573c576892539738aa0adb741d6f59a

Big Endian: https://gist.github.com/waynegerard/4cbb6d87d4ce7e81db80e5a6d798d7c7

**Comment by abalabahaha** [comment]
Discord seems to have changed this since I implemented it in 2017 :(

Thank you especially for the Gists! If you want, can you PR this to the official docs @ [discordapp/discord-api-docs](https://github.com/discordapp/discord-api-docs)?

**Comment by waynegerard** [comment]
@abalabahaha done! https://github.com/discordapp/discord-api-docs/pull/1243
