### ISSUE TITLE
guildCreate event is not listed

### ISSUE THREAD

**Issue by bsian03** [abalabahaha/eris#601]

**Comment by knht** [comment]
This is a simple documentation issue and has already been fixed on the dev branch. 👍🏼

**Comment by bsian03** [comment]
Alright - just out of curiosity, do you know where they're located?

**Comment by knht** [comment]
Documentation is generated dynamically from the JSDoc comments within the source code. You can use following 1-line command to generate docs from the dev branch yourself:

```
npm i abalabahaha/eris#dev && npx jsdoc node_modules/eris/lib/** --readme node_modules/eris/README.md -d eris-docs
```

**Comment by bsian03** [comment]
Meant for the events but that in itself answered my question so thanks 👍
