### ISSUE TITLE
ClienStatus

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#605]
Hello,
```
Eris version ==> 0.11.1
Eris Sharder ==> 1.9.0
```
ClientStatus returns to an undefined state when offline on the web, desktop and mobile.

with the following code 
```js
if (message.mentions.length === 0) {
    return message.channel.createMessage("Please mention a user");
             }
         let mem = message.channel.guild.members.get(message.mentions[0].id);
         console.log(JSON.stringify(mem.clientStatus))

**Comment by abalabahaha** [comment]
Does this happen on 0.11.2?

**Comment by ghost** [comment]
yes return undefined on the status offline

**Comment by apacheli** [comment]
This behavior is intentional as Discord doesn't send any `client_status` data for offline members.
