### ISSUE TITLE
User.avatarURL does not default

### ISSUE THREAD

**Issue by alex-taxiera** [abalabahaha/eris#636]
[The default avatar fallback was removed](https://github.com/abalabahaha/eris/pull/623/files#diff-d3d66378cfafefb2d0ff53bddebf3163L70)

**Comment by chroventer** [comment]
@abalabahaha, the corresponding pull-request has already been merged, can you close this issue?

**Comment by eritbh** [comment]
The issue should be closed automatically once the PR that fixes it lands on master with a release.
