### ISSUE TITLE
guildOnly is open, but commands from DM can be used.

### ISSUE THREAD

**Issue by ramazan-bodur** [abalabahaha/eris#661]
I use CommandClient, and although guildOnly is marked as true, commands can be used from direct messages. Please  solve this.

Note: Permissions dont work either. I set the manageGuild permission to true, but those who are not authorized to manage the server can use the command.

**Comment by apacheli** [comment]
Can you please provide us with a sample of yours?

I've created my own test and it seemed to have worked fine:
```js
const lib = require('.');

const token = 'MjM4NDk0NzU2NTIxMzc3Nzky.CunGFQ.wUILz7z6HoJzVeq6pyHPmVgQgV4';
const client = new lib.CommandClient(token, {}, {
  prefix: '==='
});

client.on('ready', () => console.log('yes'));

client.registerCommand('hello', () => {
  return 'Hello, World!';
}, {
  guildOnly: true
});

client.registerCommand('manage-guild', () => {
  return 'splish splash';
}, {
  requirements: {
    permissions: {
      manageGuild: true
    }
  }
});

client.connect();
```
Guild context:
![image](https://user-images.githubusercontent.com/43933794/76921510-3a44dd80-689c-11ea-9e38-93f82c262a7a.png)
DM context:
![image](https://user-images.githubusercontent.com/43933794/76921524-44ff7280-689c-11ea-809a-9afa3f9ae603.png)

I did get an error, though. However, it's completely unrelated to yours.
```
(node:9796) UnhandledPromiseRejectionWarning: TypeError: msg.channel.permissionsOf is not a function
```
Looking at `Command:193`, this one could easily be fixed.

**Comment by abalabahaha** [comment]
Closing due to lack of detail and inactivity
