### ISSUE TITLE
Suggestion: CommandError exception with message content

### ISSUE THREAD

**Issue by TenkenNoSoujiro** [abalabahaha/eris#662]
I suggest the addition of an `eris.CommandError` class that is an `Error` subclass that takes an `eris.MessageContent` as its constructor argument. `Command#process` method could catch this error and return the message content when encountered.

Currently I am using something like this in my own Discord bot, but have to jump through several hoops to get it to work:

```js
export class CommandClient extends eris.CommandClient {
    registerCommand(label, generator, options) {
        const command = super.registerCommand(label, generator, options);
        if (Object.getPrototypeOf(command) === eris.Command.prototype) {
            Object.setPrototypeOf(command, Command.prototype);
        }
        return command;
    }
}

export class Command extends eris.Command {
    registerSubcommand(label, generator, options) {
        const command = super.registerSubcommand(label, generator, options);
        if (Object.getPrototypeOf(command) === eris.Command.prototype) {
            Object.setPrototypeOf(command, Command.prototype);
        }
        return command;
    }

    async process(msg, args) {
        try {
            return await super.process(msg, args);
        }
        catch (e) {
            if (e instanceof CommandError) return e.content;
            throw e;
        }
    }
}

const isFormattedRegExp = /^#|^(?<mark>[*_`~]).*\k<mark>$/s;

export class CommandError extends Error {
    constructor(content) {
        super("An error occurred while processing a command.");
        // for trivial content, add emphasis to the message...
        if (typeof content === "string" && !isFormattedRegExp.test(content)) {
            content = `*${content}*`;
        }
        this.content = content;
    }
}
```

I use this capability in the following way:

```js
bot.registerCommand("command", async (msg, args) => {
   …
   const result = await doSomeWork();
   …
});
async function doSomeWork() {
   …
   // The following message is sent by the bot
   throw new CommandError("Could not perform the requested action");
}
```

**Comment by eritbh** [comment]
The capability you're looking for is already achievable with a minimal addition to your command definition:

```ts
bot.registerCommand("command", async (msg, args) => {
   …
   let result;
   try {
      result = await doSomeWork();
   } catch (error) {
      return error.message;
   }
   …
});
async function doSomeWork() {
   …
   // The following message is sent by the bot
   throw new Error("Could not perform the requested action");
}
```

Eris's command framework is not heavily used, and it's been debated in the past that it would be better to just remove it in favor of other third-party command frameworks that exist. I doubt the additions you're asking for will be accepted.

**Comment by TenkenNoSoujiro** [comment]
That has the downside of requiring `try/catch` boilerplate in every command, which was the reason I added this to my own project in the first place. I'm currently not familiar with other third-party command frameworks for eris. Is there a list of these frameworks somewhere?

**Comment by eritbh** [comment]
There's a list pinned in the Eris channel in the [API community Discord](https://discord.gg/discord-api). I'll copy-paste the message here:

> Community-Made Eris Command Frameworks:
> https://github.com/alex-taxiera/eris-boiler
> https://github.com/Geo1088/yuuko
> https://github.com/LJNeon/patron/tree/dev
> https://github.com/riyacchi/chariot.js 
> https://github.com/Khaazz/AxonCore
> https://github.com/mets11rap/cyclone-engine

**Comment by abalabahaha** [comment]
Whoops, does the `errorMessage` option of the `Command` constructor fulfill this purpose?

**Comment by bsian03** [comment]
As an extension to this - it would be good if errorMessage took an extra `error` parameter as well

**Comment by abalabahaha** [comment]
#964

**Comment by bsian03** [comment]
Well that clearly shows how much I've been keeping up with eris... 👀
