### ISSUE TITLE
ERR_UNHANDLED_ERROR after updating to 0.11.2

### ISSUE THREAD

**Issue by agarian-2** [abalabahaha/eris#673]
I seem to have run into an unusual issue after updating from 1.10.1 to 1.11.2. Seemingly out of nowhere, the bot sometimes throws this connection error, causing my game server to crash and restart.
```
[5022.558]: [INFO] An unnamed player rejoined the game! IP: ::ffff:37.192.190.132. Player ID: 464148. Players: 1.
[5068.763]: [INFO] An unnamed player has disconnected! IP: ::ffff:37.192.190.132. Players: 0.
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    readyState: 2,
    protocol: '',
    _binaryType: 'nodebuffer',
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _closeCode: 1006,
    _extensions: {},
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    url: 'wss://gateway.discord.gg/?v=6&encoding=json',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /?v=6&encoding=json HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: 3ngaXVhxFWt4sVeV0Ypl1Q==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Host: gateway.discord.gg\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/?v=6&encoding=json',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'WebSocket was closed before the connection was established',
  error: Error: WebSocket was closed before the connection was established
      at WebSocket.terminate (/home/arras/arras.io/node_modules/eris/node_modules/ws/lib/websocket.js:366:14)
      at Shard.disconnect (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:98:25)
      at Timeout._onTimeout (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:1684:22)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
})
    at Client.emit (events.js:300:17)
    at Shard.emit (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:1888:26)
    at WebSocket.ws.onerror (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:1632:18)
    at WebSocket.onError (/home/arras/arras.io/node_modules/eris/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:311:20)
    at abortHandshake (/home/arras/arras.io/node_modules/eris/node_modules/ws/lib/websocket.js:697:15)
    at WebSocket.terminate (/home/arras/arras.io/node_modules/eris/node_modules/ws/lib/websocket.js:366:14)
    at Shard.disconnect (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:98:25)
    at Timeout._onTimeout (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:1684:22)
    at listOnTimeout (internal/timers.js:549:17)
Emitted 'error' event on Client instance at:
    at Shard.emit (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:1888:26)
    at Shard.disconnect (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:109:18)
    at Timeout._onTimeout (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:1684:22)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ERR_UNHANDLED_ERROR',
  context: ErrorEvent {
    target: WebSocket {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      readyState: 2,
      protocol: '',
      _binaryType: 'nodebuffer',
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _closeCode: 1006,
      _extensions: {},
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      url: 'wss://gateway.discord.gg/?v=6&encoding=json',
      _req: [ClientRequest],
      [Symbol(kCapture)]: false
    },
    type: 'error',
    message: 'WebSocket was closed before the connection was established',
    error: Error: WebSocket was closed before the connection was established
        at WebSocket.terminate (/home/arras/arras.io/node_modules/eris/node_modules/ws/lib/websocket.js:366:14)
        at Shard.disconnect (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:98:25)
        at Timeout._onTimeout (/home/arras/arras.io/node_modules/eris/lib/gateway/Shard.js:1684:22)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7)
  }
}
[0.367]: 6100 x 6100 room initalized. Max food: 149. Max nest food: 4.
...
```
Currently, I use WebSocket version 7.2.3, though it seemed to work fine with 1.10.1. I've also noticed how the bot seemingly looses connection at random without crashing the server, instead running `bot.on("ready"...`. I'm not sure if that is normal behavior, but here's an image to represent a few times the bot has done this:
![Capture](https://user-images.githubusercontent.com/36286279/78521746-e2add980-7798-11ea-991f-c27be5f2436b.PNG)
So yeah, that's quite a mouthful. Haven't found any issues similar to this, so here I am. Maybe this is just an easy fix that's been hiding under my nose, but I haven't been able to find it.

**Comment by LJNeon** [comment]
I've seen this error a few times myself, although I'm on dev not stable.

**Comment by agarian-2** [comment]
Oh my god, I literally watched TheRealMonox's account get terminated after I reported is "hacked" spam lmao
![Capture](https://user-images.githubusercontent.com/36286279/78705469-83a4ad80-78db-11ea-9d23-2f989e550227.PNG)

**Comment by ghost** [comment]
I'm also experiencing this. Unsure why.

**Comment by agarian-2** [comment]
And so far, not one person has helped.

**Comment by Brayzure** [comment]
Because there's any number of potential causes, though nearly all of them have to do with your network connection. If you're running your bot on a local machine, ensure your network connection is stable.

**Comment by agarian-2** [comment]
I'm running it on an ExtraVM server, with a top network speed of 10 Gbps. status.extravm.com doesn't appear to show any irregular lag/latency events for my server location, so we can _maybe_ rule out connection issues? For all I know, there might be something hiding under my nose, but if it ends up not being fixable, is there at least a way to make the error not kill the process?

**Comment by abalabahaha** [comment]
Can you try the dev branch?

**Comment by LJNeon** [comment]
I've been seeing this error on the dev branch, also my goal with replying initially was to confirm that it was happening to everyone. Didn't intend to start a bunch of "me too" spam.

**Comment by agarian-2** [comment]
Can confirm that the same error has just occurred with the dev branch too.

**Comment by abalabahaha** [comment]
> is there at least a way to make the error not kill the process?

> throw er; // Unhandled 'error' event

Are you handling the error event from the Client?

This is probably related to an update Discord rolled out sometime last week that forces shards to reconnect every once in a while (~2-6 hours from testing). So disconnects are the new normal, but it should be resuming without errors almost immediately...

Can you join the Discord server? It's a little better to diagnose errors there.

**Comment by agarian-2** [comment]
Alright, where do you guys keep the link? It will probably be a while until I can join, since I need to sleep for work.

**Comment by abalabahaha** [comment]
README or website, no rush

**Comment by upscripter** [comment]
I have the same error and my bot crashes :(

**Comment by agarian-2** [comment]
I'm in the Discord server; my username is `ɦﻉɭɭƈคፕ#1505`.

**Comment by upscripter** [comment]
`Error [ERR_UNHANDLED_ERROR]: Unhandled error. (ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    readyState: 2,
    protocol: '',
    _binaryType: 'nodebuffer',
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _closeCode: 1006,
    _extensions: {},
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    url: 'wss://gateway.discord.gg/?v=6&encoding=json',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /?v=6&encoding=json HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: xPrY/8W1dkD7/8tFyBi/cg==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Host: gateway.discord.gg\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/?v=6&encoding=json',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'WebSocket was closed before the connection was established',
  error: Error: WebSocket was closed before the connection was established
      at WebSocket.terminate (/home/static-bot/node_modules/ws/lib/websocket.js:367:14)
      at Shard.disconnect (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:98:25)
      at Timeout._onTimeout (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:1684:22)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
})
    at BotClient.emit (events.js:300:17)
    at Shard.emit (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:1888:26)
    at WebSocket.ws.onerror (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:1632:18)
    at WebSocket.onError (/home/static-bot/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:311:20)
    at abortHandshake (/home/static-bot/node_modules/ws/lib/websocket.js:698:15)
    at WebSocket.terminate (/home/static-bot/node_modules/ws/lib/websocket.js:367:14)
    at Shard.disconnect (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:98:25)
    at Timeout._onTimeout (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:1684:22)
    at listOnTimeout (internal/timers.js:549:17) {
  code: 'ERR_UNHANDLED_ERROR',
  context: ErrorEvent {
    target: WebSocket {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      readyState: 2,
      protocol: '',
      _binaryType: 'nodebuffer',
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _closeCode: 1006,
      _extensions: {},
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      url: 'wss://gateway.discord.gg/?v=6&encoding=json',
      _req: [ClientRequest],
      [Symbol(kCapture)]: false
    },
    type: 'error',
    message: 'WebSocket was closed before the connection was established',
    error: Error: WebSocket was closed before the connection was established
        at WebSocket.terminate (/home/static-bot/node_modules/ws/lib/websocket.js:367:14)
        at Shard.disconnect (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:98:25)
        at Timeout._onTimeout (/home/static-bot/node_modules/eris/lib/gateway/Shard.js:1684:22)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7)
  }
}`

**Comment by upscripter** [comment]
I removed .fetchAllMembers() calls from my code and stoped recive these errors

**Comment by upscripter** [comment]
Nope, still get these errors, but not so often :( 
Is it possible, to make application doesn't crash on this error?

**Comment by abalabahaha** [comment]
> throw er; // Unhandled error event

Read the error again, and consider how you could make it stop crashing the process...

**Comment by upscripter** [comment]
> Read the error again, and consider how you could make it stop crashing the process...

I should edit the lib for this, right?

**Comment by abalabahaha** [comment]
Wrong, handle the error event (in this case from the Client)

**Comment by aosync** [comment]
In case that could help, and as requested by abal on the DAPI channel, I have a log of, notably, `debug`, `shardReady`, `shardDisconnect` and `shardResume` events with timestamps of when it happens for me [here](https://github.com/abalabahaha/eris/files/4487823/genki.log). The interesting part is from line 90 to line 621.
*Note that I am on 0.12*

**Comment by abalabahaha** [comment]
Can someone try dev branch? ab9b0a5 should fix one of the possible causes.
