### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by Ratismal** [abalabahaha/eris#81]
Custom emojis have been a thing for some time. When, if ever, can we expect to see support for them in Eris? This functionality is in place in many libs, such as discord.js. I also noticed that SnazzyPines made a pull request to implement this, but it was denied. I would really appreciate this functionality as it's something that I feel would be useful.

Discord Docs: https://discordapp.com/developers/docs/resources/guild#emoji-object
discord.js: http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/Emoji
PR: #70

**Comment by mnlkrs** [comment]
It's already a thing, abal just decided not to wrap them. 
`Guild#emojis` will give you an array of [Emoji object](https://discordapp.com/developers/docs/resources/guild#emoji-object)s

**Comment by Ratismal** [comment]
Oh shoot, I'm a dunce. Thanks!
