### ISSUE TITLE
FFmpeg cpu usage spikes

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#918]
Hi i try to make a music bot that play song from youtube. But i have a problem. Every 20 second ffmpeg cpu usage increase so much. Actually before this i have no problem like that , i used to use "discord.js" before of that. I am using FFmpeg static library 4.2.2 and i tried some older versions but nothing change.

**Comment by abalabahaha** [comment]
Is FFmpeg's CPU usage low/near-zero outside of these spikes? Might be due to how audio data is being buffered, in which case this isn't really a problem. You could try passing FFmpeg the `-re` flag to see if that smooths the CPU usage.

**Comment by ghost** [comment]
I tried this code line but something went wrong. `connection.play(stream_url,options = {inputArgs: ["-re"]});`. I watched the process in `htop` . In first time , ffmpeg process's running only 0.1s and it's closing .

**Comment by abalabahaha** [comment]
Just making sure, your code has just the options object and doesn't contain `options =`?

`connection.play(url, { inputArgs: ["-re"] });` is working fine w/ FFmpeg 4.2.2 for me. Can you check your FFmpeg install and experiment with `-re` on the CLI?

**Comment by ghost** [comment]
I checked , my FFmpeg doesn't support `-re` flag.

**Comment by ghost** [comment]
How can i install FFmpeg with advanced options ? I searched configuration options but I couldn't find that.

**Comment by knht** [comment]
You'll have to build ffmpeg from source with the appropriate flags.

There's a compilation guide on the ffmpeg website for every major OS and different build tools. 

Click here: [CompilationGuide - FFmpeg](https://trac.ffmpeg.org/wiki/CompilationGuide)

**Comment by ghost** [comment]
Thanks @riyacchi I solved my `-re` flag problem but still `connection.play(stream_url, { inputArgs : ["-re"] });` doesn't work. I deleted all the package and i reinstalled but still not working. 


EDIT: I tried to play ytdl stream with `-re` flag and it worked. But i have to run radio stream url. For example : http://sc-deephouseradio.1.fm:10164/ I didn't understand why it wasn't working. In same time, I tried the other stream links but still not working

**Comment by abalabahaha** [comment]
That radio stream seems to work fine using the same `play()` code. Feel free to join our Discord channel for help if you're still having issues.

The occasional CPU spikes this issue is about seem to be an effect of buffering somewhere in the chain, and don't seem to indicate that anything is using excessive CPU that it shouldn't be. As a workaround, forcing FFmpeg to encode in realtime (`-re`) will make CPU usage more constant.
