### ISSUE TITLE
Typescript build error in dev branch

### ISSUE THREAD

**Issue by jimchen5209** [abalabahaha/eris#923]
Typescript build failed when I switch to dev branch, while building success when eris is in latest release.

Typescript version v3.8.3

Error screenshot:
![圖片](https://user-images.githubusercontent.com/10269287/80685810-532aea80-8afa-11ea-9a43-0b9f2dc48c53.png)

**Comment by abalabahaha** [comment]
Caused by my faulty merge in #610 

In my defense, the GitHub web mergetool is not the clearest.
