### ISSUE TITLE
Playing a stream without ffmpeg installed causes the stream to stuck in a "playing" state

### ISSUE THREAD

**Issue by nfearnley** [abalabahaha/eris#954]
If ffmpeg is not installed, and I call voiceconnection.play(stream), it triggers an error "FFmpeg/avconv was not found on this system. Playback of this audio format is impossible" (as expected), but it does not clear the Piper.streams array.

This causes subsequent calls to voiceconnection.play(stream) to fail with as "Already encoding" error.

Calling voiceconnection.stopPlaying() disconnects the bot from the channel, which is not ideal.

In order to clear the stream without disconnecting, it's required to called voiceconnection.piper.stop()

What should happen is that if there is a failure to start a stream in Piper, then it should automatically call Piper.stop(), preparing piper to receive a valid stream.

**Comment by abalabahaha** [comment]
Hopefully fixed by f19e7f7, which should land in a release soon
