### ISSUE TITLE
Mentions is empty on message gotten through channel.getPins()

### ISSUE THREAD

**Issue by ejulen** [abalabahaha/eris#955]
After upgrading to Eris 0.13.1 I noticed that when getting a message through `channel.getPins()`, its `mentions` property is just an empty array. Meanwhile, getting the very same message through `channel.getMessage(pinnedMessage.id)` _does_ retrieve its mentions. As I was able to access a pinned message's mentions directly before (without going through `channel.getMessage()`), I think this might be a potential regression.

Sample code:
```js
const pins = await channel.getPins();
console.log(pins[0].mentions); // []
const pinnedMessage = await channel.getMessage(pins[0].id);
console.log(pinnedMessage.mentions); // [ { id: ... } ]
```

**Comment by bsian03** [comment]
This looks like an issue with Discord

![image](https://user-images.githubusercontent.com/24302436/82574961-c1a21c00-9b7f-11ea-96c4-347f67835d53.png)

**Comment by bsian03** [comment]
Looks to be working now

**Comment by ejulen** [comment]
I worked around it, so I'll have to take your word for it :)
