### ISSUE TITLE
Allow requestGuildMembers to accept an array of guild IDs

### ISSUE THREAD

**Issue by apacheli** [abalabahaha/eris#976]
According to the Discord Developer Documentation, this gateway command can accept an array of guild IDs.

Read more: https://discord.com/developers/docs/topics/gateway#request-guild-members

**Comment by TTtie** [comment]
You can pass an array of guild IDs directly to `Shard#requestGuildMembers(guildID, opts)` - where the `opts` are the same as for `Guild#fetchMembers`. 

However, the promisified version was made with intents in mind and accounts only for fetching members from 1 guild only, as defined in the Discord Developer Documentation - thereby, it will resolve earlier with members from one guild but not from the other. I believe that this can be easily patched up to return the requested guild members from both guilds though.

**Comment by abalabahaha** [comment]
This already technically works, but as said above this will not work with intents, which are pretty much becoming mandatory Soon:tm:
